import {
  CANONICAL_CITIES,
  PROVINCE_MAP,
  getCityBySlug as _getCityBySlug,
} from "./shared/cities";
import verticalConfig from "./vertical.config";

// US states (50 + DC). slug = lowercase 2-letter code, used at /[region].
// CITIES merges the CA canonical catalog with US_CITIES (TDL #464, Option B:
// in-bar-state attorney cities parsed from CA/FL/TX bar addresses, floor>=3).
export const REGIONS = [
  { name: "Alabama", slug: "al", province: "AL" },
  { name: "Alaska", slug: "ak", province: "AK" },
  { name: "Arizona", slug: "az", province: "AZ" },
  { name: "Arkansas", slug: "ar", province: "AR" },
  { name: "California", slug: "ca", province: "CA" },
  { name: "Colorado", slug: "co", province: "CO" },
  { name: "Connecticut", slug: "ct", province: "CT" },
  { name: "Delaware", slug: "de", province: "DE" },
  { name: "Florida", slug: "fl", province: "FL" },
  { name: "Georgia", slug: "ga", province: "GA" },
  { name: "Hawaii", slug: "hi", province: "HI" },
  { name: "Idaho", slug: "id", province: "ID" },
  { name: "Illinois", slug: "il", province: "IL" },
  { name: "Indiana", slug: "in", province: "IN" },
  { name: "Iowa", slug: "ia", province: "IA" },
  { name: "Kansas", slug: "ks", province: "KS" },
  { name: "Kentucky", slug: "ky", province: "KY" },
  { name: "Louisiana", slug: "la", province: "LA" },
  { name: "Maine", slug: "me", province: "ME" },
  { name: "Maryland", slug: "md", province: "MD" },
  { name: "Massachusetts", slug: "ma", province: "MA" },
  { name: "Michigan", slug: "mi", province: "MI" },
  { name: "Minnesota", slug: "mn", province: "MN" },
  { name: "Mississippi", slug: "ms", province: "MS" },
  { name: "Missouri", slug: "mo", province: "MO" },
  { name: "Montana", slug: "mt", province: "MT" },
  { name: "Nebraska", slug: "ne", province: "NE" },
  { name: "Nevada", slug: "nv", province: "NV" },
  { name: "New Hampshire", slug: "nh", province: "NH" },
  { name: "New Jersey", slug: "nj", province: "NJ" },
  { name: "New Mexico", slug: "nm", province: "NM" },
  { name: "New York", slug: "ny", province: "NY" },
  { name: "North Carolina", slug: "nc", province: "NC" },
  { name: "North Dakota", slug: "nd", province: "ND" },
  { name: "Ohio", slug: "oh", province: "OH" },
  { name: "Oklahoma", slug: "ok", province: "OK" },
  { name: "Oregon", slug: "or", province: "OR" },
  { name: "Pennsylvania", slug: "pa", province: "PA" },
  { name: "Rhode Island", slug: "ri", province: "RI" },
  { name: "South Carolina", slug: "sc", province: "SC" },
  { name: "South Dakota", slug: "sd", province: "SD" },
  { name: "Tennessee", slug: "tn", province: "TN" },
  { name: "Texas", slug: "tx", province: "TX" },
  { name: "Utah", slug: "ut", province: "UT" },
  { name: "Vermont", slug: "vt", province: "VT" },
  { name: "Virginia", slug: "va", province: "VA" },
  { name: "Washington", slug: "wa", province: "WA" },
  { name: "West Virginia", slug: "wv", province: "WV" },
  { name: "Wisconsin", slug: "wi", province: "WI" },
  { name: "Wyoming", slug: "wy", province: "WY" },
  { name: "District of Columbia", slug: "dc", province: "DC" },
];

export const US_CITIES = [
  { name: "Acton", slug: "acton", province: "CA", listing_count: 9 },
  { name: "Adelanto", slug: "adelanto", province: "CA", listing_count: 8 },
  { name: "Agoura Hills", slug: "agoura-hills", province: "CA", listing_count: 405 },
  { name: "Ahwahnee", slug: "ahwahnee", province: "CA", listing_count: 3 },
  { name: "Alameda", slug: "alameda", province: "CA", listing_count: 285 },
  { name: "Alamo", slug: "alamo", province: "CA", listing_count: 86 },
  { name: "Albany", slug: "albany", province: "CA", listing_count: 78 },
  { name: "Alhambra", slug: "alhambra", province: "CA", listing_count: 138 },
  { name: "Aliso Viejo", slug: "aliso-viejo", province: "CA", listing_count: 297 },
  { name: "Alpine", slug: "alpine", province: "CA", listing_count: 22 },
  { name: "Alta Loma", slug: "alta-loma", province: "CA", listing_count: 3 },
  { name: "Altadena", slug: "altadena", province: "CA", listing_count: 34 },
  { name: "Alturas", slug: "alturas", province: "CA", listing_count: 5 },
  { name: "Alviso", slug: "alviso", province: "CA", listing_count: 16 },
  { name: "Amador City", slug: "amador-city", province: "CA", listing_count: 6 },
  { name: "American Canyon", slug: "american-canyon", province: "CA", listing_count: 7 },
  { name: "American Cyn", slug: "american-cyn", province: "CA", listing_count: 4 },
  { name: "Anaheim", slug: "anaheim", province: "CA", listing_count: 499 },
  { name: "Anaheim Hills", slug: "anaheim-hills", province: "CA", listing_count: 15 },
  { name: "Angels Camp", slug: "angels-camp", province: "CA", listing_count: 3 },
  { name: "Antelope", slug: "antelope", province: "CA", listing_count: 3 },
  { name: "Antioch", slug: "antioch", province: "CA", listing_count: 33 },
  { name: "Apple Valley", slug: "apple-valley", province: "CA", listing_count: 24 },
  { name: "Aptos", slug: "aptos", province: "CA", listing_count: 86 },
  { name: "Arcadia", slug: "arcadia", province: "CA", listing_count: 183 },
  { name: "Arcata", slug: "arcata", province: "CA", listing_count: 25 },
  { name: "Aromas", slug: "aromas", province: "CA", listing_count: 3 },
  { name: "Arroyo Grande", slug: "arroyo-grande", province: "CA", listing_count: 50 },
  { name: "Artesia", slug: "artesia", province: "CA", listing_count: 11 },
  { name: "Atascadero", slug: "atascadero", province: "CA", listing_count: 33 },
  { name: "Atherton", slug: "atherton", province: "CA", listing_count: 27 },
  { name: "Atwater", slug: "atwater", province: "CA", listing_count: 4 },
  { name: "Auburn", slug: "auburn", province: "CA", listing_count: 151 },
  { name: "Avalon", slug: "avalon", province: "CA", listing_count: 4 },
  { name: "Avila Beach", slug: "avila-beach", province: "CA", listing_count: 8 },
  { name: "Azusa", slug: "azusa", province: "CA", listing_count: 20 },
  { name: "Bakersfield", slug: "bakersfield", province: "CA", listing_count: 692 },
  { name: "Baldwin Park", slug: "baldwin-park", province: "CA", listing_count: 15 },
  { name: "Banning", slug: "banning", province: "CA", listing_count: 37 },
  { name: "Barstow", slug: "barstow", province: "CA", listing_count: 7 },
  { name: "Beaumont", slug: "beaumont", province: "CA", listing_count: 21 },
  { name: "Bel Tiburon", slug: "bel-tiburon", province: "CA", listing_count: 85 },
  { name: "Bell Canyon", slug: "bell-canyon", province: "CA", listing_count: 14 },
  { name: "Bell Gardens", slug: "bell-gardens", province: "CA", listing_count: 11 },
  { name: "Bellflower", slug: "bellflower", province: "CA", listing_count: 36 },
  { name: "Belmont", slug: "belmont", province: "CA", listing_count: 103 },
  { name: "Belvedere Tiburon", slug: "belvedere-tiburon", province: "CA", listing_count: 9 },
  { name: "Ben Lomond", slug: "ben-lomond", province: "CA", listing_count: 7 },
  { name: "Benicia", slug: "benicia", province: "CA", listing_count: 71 },
  { name: "Berkeley", slug: "berkeley", province: "CA", listing_count: 935 },
  { name: "Bermuda Dunes", slug: "bermuda-dunes", province: "CA", listing_count: 10 },
  { name: "Bethel Island", slug: "bethel-island", province: "CA", listing_count: 5 },
  { name: "Beverly Hills", slug: "beverly-hills", province: "CA", listing_count: 2342 },
  { name: "Big Bear City", slug: "big-bear-city", province: "CA", listing_count: 5 },
  { name: "Big Bear Lake", slug: "big-bear-lake", province: "CA", listing_count: 12 },
  { name: "Bishop", slug: "bishop", province: "CA", listing_count: 21 },
  { name: "Blrsdn Greagl", slug: "blrsdn-greagl", province: "CA", listing_count: 3 },
  { name: "Blue Jay", slug: "blue-jay", province: "CA", listing_count: 7 },
  { name: "Blythe", slug: "blythe", province: "CA", listing_count: 5 },
  { name: "Bodega", slug: "bodega", province: "CA", listing_count: 3 },
  { name: "Bodega Bay", slug: "bodega-bay", province: "CA", listing_count: 8 },
  { name: "Bolinas", slug: "bolinas", province: "CA", listing_count: 7 },
  { name: "Bonita", slug: "bonita", province: "CA", listing_count: 35 },
  { name: "Bonsall", slug: "bonsall", province: "CA", listing_count: 22 },
  { name: "Borrego Springs", slug: "borrego-springs", province: "CA", listing_count: 4 },
  { name: "Boulder Creek", slug: "boulder-creek", province: "CA", listing_count: 7 },
  { name: "Bowman", slug: "bowman", province: "CA", listing_count: 3 },
  { name: "Bradbury", slug: "bradbury", province: "CA", listing_count: 4 },
  { name: "Brawley", slug: "brawley", province: "CA", listing_count: 5 },
  { name: "Brea", slug: "brea", province: "CA", listing_count: 309 },
  { name: "Brentwood", slug: "brentwood", province: "CA", listing_count: 55 },
  { name: "Brisbane", slug: "brisbane", province: "CA", listing_count: 29 },
  { name: "Brooks", slug: "brooks", province: "CA", listing_count: 3 },
  { name: "Buellton", slug: "buellton", province: "CA", listing_count: 5 },
  { name: "Buena Park", slug: "buena-park", province: "CA", listing_count: 56 },
  { name: "Burbank", slug: "burbank", province: "CA", listing_count: 1232 },
  { name: "Burlingame", slug: "burlingame", province: "CA", listing_count: 324 },
  { name: "Ca", slug: "ca", province: "CA", listing_count: 15 },
  { name: "Calabasas", slug: "calabasas", province: "CA", listing_count: 538 },
  { name: "Calexico", slug: "calexico", province: "CA", listing_count: 5 },
  { name: "Calimesa", slug: "calimesa", province: "CA", listing_count: 3 },
  { name: "Calistoga", slug: "calistoga", province: "CA", listing_count: 10 },
  { name: "Camarillo", slug: "camarillo", province: "CA", listing_count: 216 },
  { name: "Cambria", slug: "cambria", province: "CA", listing_count: 17 },
  { name: "Cameron Park", slug: "cameron-park", province: "CA", listing_count: 21 },
  { name: "Camino", slug: "camino", province: "CA", listing_count: 3 },
  { name: "Camp Pendleton", slug: "camp-pendleton", province: "CA", listing_count: 8 },
  { name: "Campbell", slug: "campbell", province: "CA", listing_count: 227 },
  { name: "Canoga Park", slug: "canoga-park", province: "CA", listing_count: 48 },
  { name: "Canyon Cntry", slug: "canyon-cntry", province: "CA", listing_count: 28 },
  { name: "Canyon Country", slug: "canyon-country", province: "CA", listing_count: 4 },
  { name: "Canyon Lake", slug: "canyon-lake", province: "CA", listing_count: 10 },
  { name: "Capistrano Beach", slug: "capistrano-beach", province: "CA", listing_count: 22 },
  { name: "Capitola", slug: "capitola", province: "CA", listing_count: 31 },
  { name: "Cardiff", slug: "cardiff", province: "CA", listing_count: 53 },
  { name: "Cardiff By The Sea", slug: "cardiff-by-the-sea", province: "CA", listing_count: 6 },
  { name: "Carlsbad", slug: "carlsbad", province: "CA", listing_count: 764 },
  { name: "Carmel", slug: "carmel", province: "CA", listing_count: 60 },
  { name: "Carmel By The", slug: "carmel-by-the", province: "CA", listing_count: 11 },
  { name: "Carmel By The Sea", slug: "carmel-by-the-sea", province: "CA", listing_count: 5 },
  { name: "Carmel Valley", slug: "carmel-valley", province: "CA", listing_count: 21 },
  { name: "Carmichael", slug: "carmichael", province: "CA", listing_count: 90 },
  { name: "Carnelian Bay", slug: "carnelian-bay", province: "CA", listing_count: 5 },
  { name: "Carpinteria", slug: "carpinteria", province: "CA", listing_count: 29 },
  { name: "Carson", slug: "carson", province: "CA", listing_count: 61 },
  { name: "Castaic", slug: "castaic", province: "CA", listing_count: 9 },
  { name: "Castro Valley", slug: "castro-valley", province: "CA", listing_count: 76 },
  { name: "Cathedral City", slug: "cathedral-city", province: "CA", listing_count: 27 },
  { name: "Cayucos", slug: "cayucos", province: "CA", listing_count: 7 },
  { name: "Cazadero", slug: "cazadero", province: "CA", listing_count: 4 },
  { name: "Cedar Ridge", slug: "cedar-ridge", province: "CA", listing_count: 4 },
  { name: "Century City", slug: "century-city", province: "CA", listing_count: 53 },
  { name: "Ceres", slug: "ceres", province: "CA", listing_count: 3 },
  { name: "Cerritos", slug: "cerritos", province: "CA", listing_count: 249 },
  { name: "Chatsworth", slug: "chatsworth", province: "CA", listing_count: 136 },
  { name: "Chico", slug: "chico", province: "CA", listing_count: 213 },
  { name: "Chino", slug: "chino", province: "CA", listing_count: 51 },
  { name: "Chino Hills", slug: "chino-hills", province: "CA", listing_count: 85 },
  { name: "Chula Vista", slug: "chula-vista", province: "CA", listing_count: 278 },
  { name: "Citrus Heights", slug: "citrus-heights", province: "CA", listing_count: 6 },
  { name: "Citrus Hts", slug: "citrus-hts", province: "CA", listing_count: 37 },
  { name: "City Industry", slug: "city-industry", province: "CA", listing_count: 87 },
  { name: "City Of Industry", slug: "city-of-industry", province: "CA", listing_count: 28 },
  { name: "Claremont", slug: "claremont", province: "CA", listing_count: 154 },
  { name: "Clayton", slug: "clayton", province: "CA", listing_count: 17 },
  { name: "Clio", slug: "clio", province: "CA", listing_count: 3 },
  { name: "Cloverdale", slug: "cloverdale", province: "CA", listing_count: 12 },
  { name: "Clovis", slug: "clovis", province: "CA", listing_count: 102 },
  { name: "Cmp Pendleton", slug: "cmp-pendleton", province: "CA", listing_count: 5 },
  { name: "Coachella", slug: "coachella", province: "CA", listing_count: 5 },
  { name: "Coarsegold", slug: "coarsegold", province: "CA", listing_count: 3 },
  { name: "Colton", slug: "colton", province: "CA", listing_count: 12 },
  { name: "Colusa", slug: "colusa", province: "CA", listing_count: 13 },
  { name: "Commerce", slug: "commerce", province: "CA", listing_count: 40 },
  { name: "Compton", slug: "compton", province: "CA", listing_count: 63 },
  { name: "Concord", slug: "concord", province: "CA", listing_count: 323 },
  { name: "Copperopolis", slug: "copperopolis", province: "CA", listing_count: 3 },
  { name: "Corning", slug: "corning", province: "CA", listing_count: 4 },
  { name: "Corona", slug: "corona", province: "CA", listing_count: 238 },
  { name: "Corona Del Mar", slug: "corona-del-mar", province: "CA", listing_count: 109 },
  { name: "Coronado", slug: "coronado", province: "CA", listing_count: 81 },
  { name: "Corte Madera", slug: "corte-madera", province: "CA", listing_count: 79 },
  { name: "Costa Mesa", slug: "costa-mesa", province: "CA", listing_count: 1314 },
  { name: "Cotati", slug: "cotati", province: "CA", listing_count: 13 },
  { name: "Coto De Caza", slug: "coto-de-caza", province: "CA", listing_count: 5 },
  { name: "Covina", slug: "covina", province: "CA", listing_count: 153 },
  { name: "Crescent City", slug: "crescent-city", province: "CA", listing_count: 32 },
  { name: "Crestline", slug: "crestline", province: "CA", listing_count: 9 },
  { name: "Culver City", slug: "culver-city", province: "CA", listing_count: 735 },
  { name: "Cupertino", slug: "cupertino", province: "CA", listing_count: 345 },
  { name: "Cypress", slug: "cypress", province: "CA", listing_count: 100 },
  { name: "Daly City", slug: "daly-city", province: "CA", listing_count: 78 },
  { name: "Dana Point", slug: "dana-point", province: "CA", listing_count: 132 },
  { name: "Danville", slug: "danville", province: "CA", listing_count: 220 },
  { name: "Davis", slug: "davis", province: "CA", listing_count: 242 },
  { name: "Del Mar", slug: "del-mar", province: "CA", listing_count: 154 },
  { name: "Delano", slug: "delano", province: "CA", listing_count: 7 },
  { name: "Diablo", slug: "diablo", province: "CA", listing_count: 10 },
  { name: "Diamond Bar", slug: "diamond-bar", province: "CA", listing_count: 166 },
  { name: "Diamond Springs", slug: "diamond-springs", province: "CA", listing_count: 4 },
  { name: "Dinuba", slug: "dinuba", province: "CA", listing_count: 4 },
  { name: "Discovery Bay", slug: "discovery-bay", province: "CA", listing_count: 14 },
  { name: "Dixon", slug: "dixon", province: "CA", listing_count: 9 },
  { name: "Downey", slug: "downey", province: "CA", listing_count: 116 },
  { name: "Dsrt Hot Springs", slug: "dsrt-hot-springs", province: "CA", listing_count: 5 },
  { name: "Duarte", slug: "duarte", province: "CA", listing_count: 27 },
  { name: "Dublin", slug: "dublin", province: "CA", listing_count: 122 },
  { name: "E Palo Alto", slug: "e-palo-alto", province: "CA", listing_count: 29 },
  { name: "East Palo Alto", slug: "east-palo-alto", province: "CA", listing_count: 8 },
  { name: "Eastvale", slug: "eastvale", province: "CA", listing_count: 19 },
  { name: "Edwards", slug: "edwards", province: "CA", listing_count: 3 },
  { name: "El Cajon", slug: "el-cajon", province: "CA", listing_count: 176 },
  { name: "El Centro", slug: "el-centro", province: "CA", listing_count: 85 },
  { name: "El Cerrito", slug: "el-cerrito", province: "CA", listing_count: 63 },
  { name: "El Dorado", slug: "el-dorado", province: "CA", listing_count: 4 },
  { name: "El Dorado Hills", slug: "el-dorado-hills", province: "CA", listing_count: 133 },
  { name: "El Granada", slug: "el-granada", province: "CA", listing_count: 9 },
  { name: "El Macero", slug: "el-macero", province: "CA", listing_count: 8 },
  { name: "El Monte", slug: "el-monte", province: "CA", listing_count: 68 },
  { name: "El Segundo", slug: "el-segundo", province: "CA", listing_count: 737 },
  { name: "El Sobrante", slug: "el-sobrante", province: "CA", listing_count: 18 },
  { name: "El Verano", slug: "el-verano", province: "CA", listing_count: 3 },
  { name: "Elk", slug: "elk", province: "CA", listing_count: 4 },
  { name: "Elk Grove", slug: "elk-grove", province: "CA", listing_count: 173 },
  { name: "Elverta", slug: "elverta", province: "CA", listing_count: 4 },
  { name: "Emerald Hills", slug: "emerald-hills", province: "CA", listing_count: 14 },
  { name: "Emeryville", slug: "emeryville", province: "CA", listing_count: 240 },
  { name: "Encinitas", slug: "encinitas", province: "CA", listing_count: 314 },
  { name: "Encino", slug: "encino", province: "CA", listing_count: 1262 },
  { name: "Escalon", slug: "escalon", province: "CA", listing_count: 7 },
  { name: "Escondido", slug: "escondido", province: "CA", listing_count: 228 },
  { name: "Eureka", slug: "eureka", province: "CA", listing_count: 139 },
  { name: "Exeter", slug: "exeter", province: "CA", listing_count: 3 },
  { name: "Fair Oaks", slug: "fair-oaks", province: "CA", listing_count: 107 },
  { name: "Fairfax", slug: "fairfax", province: "CA", listing_count: 34 },
  { name: "Fairfield", slug: "fairfield", province: "CA", listing_count: 245 },
  { name: "Fairview", slug: "fairview", province: "CA", listing_count: 4 },
  { name: "Fallbrook", slug: "fallbrook", province: "CA", listing_count: 51 },
  { name: "Felton", slug: "felton", province: "CA", listing_count: 7 },
  { name: "Ferndale", slug: "ferndale", province: "CA", listing_count: 4 },
  { name: "Fillmore", slug: "fillmore", province: "CA", listing_count: 4 },
  { name: "Folsom", slug: "folsom", province: "CA", listing_count: 270 },
  { name: "Fontana", slug: "fontana", province: "CA", listing_count: 32 },
  { name: "Foothill Ranch", slug: "foothill-ranch", province: "CA", listing_count: 15 },
  { name: "Foothill Rnch", slug: "foothill-rnch", province: "CA", listing_count: 47 },
  { name: "Forestville", slug: "forestville", province: "CA", listing_count: 9 },
  { name: "Fort Bragg", slug: "fort-bragg", province: "CA", listing_count: 21 },
  { name: "Fortuna", slug: "fortuna", province: "CA", listing_count: 7 },
  { name: "Foster City", slug: "foster-city", province: "CA", listing_count: 196 },
  { name: "Fountain Valley", slug: "fountain-valley", province: "CA", listing_count: 28 },
  { name: "Fountain Vly", slug: "fountain-vly", province: "CA", listing_count: 107 },
  { name: "Fowler", slug: "fowler", province: "CA", listing_count: 3 },
  { name: "Freedom", slug: "freedom", province: "CA", listing_count: 3 },
  { name: "Fremont", slug: "fremont", province: "CA", listing_count: 306 },
  { name: "French Camp", slug: "french-camp", province: "CA", listing_count: 6 },
  { name: "Fresno", slug: "fresno", province: "CA", listing_count: 1676 },
  { name: "Friant", slug: "friant", province: "CA", listing_count: 3 },
  { name: "Fullerton", slug: "fullerton", province: "CA", listing_count: 279 },
  { name: "Galt", slug: "galt", province: "CA", listing_count: 10 },
  { name: "Garden Grove", slug: "garden-grove", province: "CA", listing_count: 148 },
  { name: "Gardena", slug: "gardena", province: "CA", listing_count: 71 },
  { name: "Gilroy", slug: "gilroy", province: "CA", listing_count: 27 },
  { name: "Glen Ellen", slug: "glen-ellen", province: "CA", listing_count: 10 },
  { name: "Glendale", slug: "glendale", province: "CA", listing_count: 1815 },
  { name: "Glendora", slug: "glendora", province: "CA", listing_count: 60 },
  { name: "Gold River", slug: "gold-river", province: "CA", listing_count: 108 },
  { name: "Goleta", slug: "goleta", province: "CA", listing_count: 63 },
  { name: "Granada Hills", slug: "granada-hills", province: "CA", listing_count: 94 },
  { name: "Grand Terrace", slug: "grand-terrace", province: "CA", listing_count: 7 },
  { name: "Granite Bay", slug: "granite-bay", province: "CA", listing_count: 76 },
  { name: "Grass Valley", slug: "grass-valley", province: "CA", listing_count: 64 },
  { name: "Graton", slug: "graton", province: "CA", listing_count: 4 },
  { name: "Greenbrae", slug: "greenbrae", province: "CA", listing_count: 57 },
  { name: "Greenfield", slug: "greenfield", province: "CA", listing_count: 3 },
  { name: "Gridley", slug: "gridley", province: "CA", listing_count: 3 },
  { name: "Grover Beach", slug: "grover-beach", province: "CA", listing_count: 13 },
  { name: "Gualala", slug: "gualala", province: "CA", listing_count: 4 },
  { name: "Guerneville", slug: "guerneville", province: "CA", listing_count: 5 },
  { name: "Hacienda Hts", slug: "hacienda-hts", province: "CA", listing_count: 24 },
  { name: "Half Moon Bay", slug: "half-moon-bay", province: "CA", listing_count: 52 },
  { name: "Hanford", slug: "hanford", province: "CA", listing_count: 85 },
  { name: "Harbor City", slug: "harbor-city", province: "CA", listing_count: 9 },
  { name: "Hawthorne", slug: "hawthorne", province: "CA", listing_count: 61 },
  { name: "Hayward", slug: "hayward", province: "CA", listing_count: 140 },
  { name: "Healdsburg", slug: "healdsburg", province: "CA", listing_count: 50 },
  { name: "Hemet", slug: "hemet", province: "CA", listing_count: 34 },
  { name: "Hercules", slug: "hercules", province: "CA", listing_count: 23 },
  { name: "Hermosa Beach", slug: "hermosa-beach", province: "CA", listing_count: 162 },
  { name: "Hesperia", slug: "hesperia", province: "CA", listing_count: 9 },
  { name: "Hidden Hills", slug: "hidden-hills", province: "CA", listing_count: 12 },
  { name: "Highland", slug: "highland", province: "CA", listing_count: 19 },
  { name: "Hillsborough", slug: "hillsborough", province: "CA", listing_count: 50 },
  { name: "Hollister", slug: "hollister", province: "CA", listing_count: 46 },
  { name: "Hollywood", slug: "hollywood", province: "CA", listing_count: 9 },
  { name: "Huntington Beach", slug: "huntington-beach", province: "CA", listing_count: 493 },
  { name: "Huntington Park", slug: "huntington-park", province: "CA", listing_count: 5 },
  { name: "Huntington Pk", slug: "huntington-pk", province: "CA", listing_count: 12 },
  { name: "Idyllwild", slug: "idyllwild", province: "CA", listing_count: 9 },
  { name: "Imperial", slug: "imperial", province: "CA", listing_count: 11 },
  { name: "Imperial Beach", slug: "imperial-beach", province: "CA", listing_count: 12 },
  { name: "Independence", slug: "independence", province: "CA", listing_count: 5 },
  { name: "Indian Wells", slug: "indian-wells", province: "CA", listing_count: 86 },
  { name: "Indio", slug: "indio", province: "CA", listing_count: 151 },
  { name: "Industry", slug: "industry", province: "CA", listing_count: 3 },
  { name: "Inglewood", slug: "inglewood", province: "CA", listing_count: 119 },
  { name: "Inverness", slug: "inverness", province: "CA", listing_count: 3 },
  { name: "Irvine", slug: "irvine", province: "CA", listing_count: 5519 },
  { name: "Jackson", slug: "jackson", province: "CA", listing_count: 32 },
  { name: "Jamul", slug: "jamul", province: "CA", listing_count: 7 },
  { name: "Joshua Tree", slug: "joshua-tree", province: "CA", listing_count: 13 },
  { name: "Julian", slug: "julian", province: "CA", listing_count: 9 },
  { name: "Jurupa Valley", slug: "jurupa-valley", province: "CA", listing_count: 16 },
  { name: "Keene", slug: "keene", province: "CA", listing_count: 5 },
  { name: "Kelseyville", slug: "kelseyville", province: "CA", listing_count: 11 },
  { name: "Kensington", slug: "kensington", province: "CA", listing_count: 20 },
  { name: "Kentfield", slug: "kentfield", province: "CA", listing_count: 34 },
  { name: "Kenwood", slug: "kenwood", province: "CA", listing_count: 6 },
  { name: "Kerman", slug: "kerman", province: "CA", listing_count: 5 },
  { name: "Kernville", slug: "kernville", province: "CA", listing_count: 4 },
  { name: "Kings Beach", slug: "kings-beach", province: "CA", listing_count: 4 },
  { name: "Kingsburg", slug: "kingsburg", province: "CA", listing_count: 3 },
  { name: "Klamath", slug: "klamath", province: "CA", listing_count: 7 },
  { name: "La Ca Ada Flintridge", slug: "la-ca-ada-flintridge", province: "CA", listing_count: 3 },
  { name: "La Canada", slug: "la-canada", province: "CA", listing_count: 20 },
  { name: "La Canada Flintridge", slug: "la-canada-flintridge", province: "CA", listing_count: 34 },
  { name: "La Canada Flt", slug: "la-canada-flt", province: "CA", listing_count: 111 },
  { name: "La Crescenta", slug: "la-crescenta", province: "CA", listing_count: 85 },
  { name: "La Habra", slug: "la-habra", province: "CA", listing_count: 45 },
  { name: "La Habra Hgts", slug: "la-habra-hgts", province: "CA", listing_count: 3 },
  { name: "La Honda", slug: "la-honda", province: "CA", listing_count: 4 },
  { name: "La Jolla", slug: "la-jolla", province: "CA", listing_count: 564 },
  { name: "La Mesa", slug: "la-mesa", province: "CA", listing_count: 191 },
  { name: "La Mirada", slug: "la-mirada", province: "CA", listing_count: 40 },
  { name: "La Palma", slug: "la-palma", province: "CA", listing_count: 33 },
  { name: "La Puente", slug: "la-puente", province: "CA", listing_count: 14 },
  { name: "La Quinta", slug: "la-quinta", province: "CA", listing_count: 77 },
  { name: "La Verne", slug: "la-verne", province: "CA", listing_count: 40 },
  { name: "Ladera Ranch", slug: "ladera-ranch", province: "CA", listing_count: 167 },
  { name: "Lafayette", slug: "lafayette", province: "CA", listing_count: 263 },
  { name: "Laguna Beach", slug: "laguna-beach", province: "CA", listing_count: 243 },
  { name: "Laguna Hills", slug: "laguna-hills", province: "CA", listing_count: 182 },
  { name: "Laguna Niguel", slug: "laguna-niguel", province: "CA", listing_count: 216 },
  { name: "Laguna Woods", slug: "laguna-woods", province: "CA", listing_count: 25 },
  { name: "Lake Arrowhead", slug: "lake-arrowhead", province: "CA", listing_count: 7 },
  { name: "Lake Balboa", slug: "lake-balboa", province: "CA", listing_count: 3 },
  { name: "Lake Elsinore", slug: "lake-elsinore", province: "CA", listing_count: 11 },
  { name: "Lake Forest", slug: "lake-forest", province: "CA", listing_count: 186 },
  { name: "Lake Sherwood", slug: "lake-sherwood", province: "CA", listing_count: 5 },
  { name: "Lakeport", slug: "lakeport", province: "CA", listing_count: 43 },
  { name: "Lakeside", slug: "lakeside", province: "CA", listing_count: 19 },
  { name: "Lakewood", slug: "lakewood", province: "CA", listing_count: 42 },
  { name: "Lamont", slug: "lamont", province: "CA", listing_count: 5 },
  { name: "Lancaster", slug: "lancaster", province: "CA", listing_count: 132 },
  { name: "Larkspur", slug: "larkspur", province: "CA", listing_count: 94 },
  { name: "Lathrop", slug: "lathrop", province: "CA", listing_count: 3 },
  { name: "Lawndale", slug: "lawndale", province: "CA", listing_count: 27 },
  { name: "Lemon Grove", slug: "lemon-grove", province: "CA", listing_count: 11 },
  { name: "Lemoore", slug: "lemoore", province: "CA", listing_count: 3 },
  { name: "Lincoln", slug: "lincoln", province: "CA", listing_count: 46 },
  { name: "Linden", slug: "linden", province: "CA", listing_count: 5 },
  { name: "Littlerock", slug: "littlerock", province: "CA", listing_count: 3 },
  { name: "Livermore", slug: "livermore", province: "CA", listing_count: 89 },
  { name: "Livingston", slug: "livingston", province: "CA", listing_count: 4 },
  { name: "Lk Arrowhead", slug: "lk-arrowhead", province: "CA", listing_count: 10 },
  { name: "Lodi", slug: "lodi", province: "CA", listing_count: 60 },
  { name: "Loma Linda", slug: "loma-linda", province: "CA", listing_count: 29 },
  { name: "Lomita", slug: "lomita", province: "CA", listing_count: 16 },
  { name: "Lompoc", slug: "lompoc", province: "CA", listing_count: 21 },
  { name: "Long Beach", slug: "long-beach", province: "CA", listing_count: 1429 },
  { name: "Loomis", slug: "loomis", province: "CA", listing_count: 31 },
  { name: "Los Alamitos", slug: "los-alamitos", province: "CA", listing_count: 90 },
  { name: "Los Altos", slug: "los-altos", province: "CA", listing_count: 275 },
  { name: "Los Altos Hills", slug: "los-altos-hills", province: "CA", listing_count: 35 },
  { name: "Los Angeles", slug: "los-angeles", province: "CA", listing_count: 27195 },
  { name: "Los Angles", slug: "los-angles", province: "CA", listing_count: 6 },
  { name: "Los Banos", slug: "los-banos", province: "CA", listing_count: 10 },
  { name: "Los Gatos", slug: "los-gatos", province: "CA", listing_count: 319 },
  { name: "Los Olivos", slug: "los-olivos", province: "CA", listing_count: 11 },
  { name: "Los Osos", slug: "los-osos", province: "CA", listing_count: 20 },
  { name: "Lower Lake", slug: "lower-lake", province: "CA", listing_count: 6 },
  { name: "Madera", slug: "madera", province: "CA", listing_count: 81 },
  { name: "Malibu", slug: "malibu", province: "CA", listing_count: 171 },
  { name: "Mammoth Lakes", slug: "mammoth-lakes", province: "CA", listing_count: 22 },
  { name: "Manhattan Beach", slug: "manhattan-beach", province: "CA", listing_count: 481 },
  { name: "Manteca", slug: "manteca", province: "CA", listing_count: 24 },
  { name: "Marina", slug: "marina", province: "CA", listing_count: 15 },
  { name: "Marina Del Rey", slug: "marina-del-rey", province: "CA", listing_count: 271 },
  { name: "Mariposa", slug: "mariposa", province: "CA", listing_count: 10 },
  { name: "Markleeville", slug: "markleeville", province: "CA", listing_count: 4 },
  { name: "Martinez", slug: "martinez", province: "CA", listing_count: 337 },
  { name: "Marysville", slug: "marysville", province: "CA", listing_count: 57 },
  { name: "Mather", slug: "mather", province: "CA", listing_count: 27 },
  { name: "Mcclellan", slug: "mcclellan", province: "CA", listing_count: 9 },
  { name: "Mckinleyville", slug: "mckinleyville", province: "CA", listing_count: 13 },
  { name: "Meadow Vista", slug: "meadow-vista", province: "CA", listing_count: 8 },
  { name: "Mendocino", slug: "mendocino", province: "CA", listing_count: 11 },
  { name: "Menifee", slug: "menifee", province: "CA", listing_count: 32 },
  { name: "Menlo Park", slug: "menlo-park", province: "CA", listing_count: 872 },
  { name: "Merced", slug: "merced", province: "CA", listing_count: 115 },
  { name: "Middletown", slug: "middletown", province: "CA", listing_count: 3 },
  { name: "Mill Valley", slug: "mill-valley", province: "CA", listing_count: 262 },
  { name: "Millbrae", slug: "millbrae", province: "CA", listing_count: 74 },
  { name: "Milpitas", slug: "milpitas", province: "CA", listing_count: 71 },
  { name: "Miranda", slug: "miranda", province: "CA", listing_count: 3 },
  { name: "Mission Hills", slug: "mission-hills", province: "CA", listing_count: 21 },
  { name: "Mission Viejo", slug: "mission-viejo", province: "CA", listing_count: 241 },
  { name: "Modesto", slug: "modesto", province: "CA", listing_count: 434 },
  { name: "Moffett Field", slug: "moffett-field", province: "CA", listing_count: 5 },
  { name: "Mojave", slug: "mojave", province: "CA", listing_count: 4 },
  { name: "Mokelumne Hl", slug: "mokelumne-hl", province: "CA", listing_count: 3 },
  { name: "Monarch Beach", slug: "monarch-beach", province: "CA", listing_count: 4 },
  { name: "Monrovia", slug: "monrovia", province: "CA", listing_count: 115 },
  { name: "Montara", slug: "montara", province: "CA", listing_count: 9 },
  { name: "Montclair", slug: "montclair", province: "CA", listing_count: 11 },
  { name: "Monte Rio", slug: "monte-rio", province: "CA", listing_count: 4 },
  { name: "Monte Sereno", slug: "monte-sereno", province: "CA", listing_count: 17 },
  { name: "Montebello", slug: "montebello", province: "CA", listing_count: 62 },
  { name: "Montecito", slug: "montecito", province: "CA", listing_count: 4 },
  { name: "Monterey", slug: "monterey", province: "CA", listing_count: 215 },
  { name: "Monterey Park", slug: "monterey-park", province: "CA", listing_count: 561 },
  { name: "Montrose", slug: "montrose", province: "CA", listing_count: 47 },
  { name: "Moorpark", slug: "moorpark", province: "CA", listing_count: 50 },
  { name: "Moraga", slug: "moraga", province: "CA", listing_count: 90 },
  { name: "Moreno Valley", slug: "moreno-valley", province: "CA", listing_count: 39 },
  { name: "Morgan Hill", slug: "morgan-hill", province: "CA", listing_count: 76 },
  { name: "Morro Bay", slug: "morro-bay", province: "CA", listing_count: 23 },
  { name: "Moss Beach", slug: "moss-beach", province: "CA", listing_count: 9 },
  { name: "Mount Shasta", slug: "mount-shasta", province: "CA", listing_count: 13 },
  { name: "Mountain View", slug: "mountain-view", province: "CA", listing_count: 770 },
  { name: "Murphys", slug: "murphys", province: "CA", listing_count: 7 },
  { name: "Murrieta", slug: "murrieta", province: "CA", listing_count: 232 },
  { name: "N Hollywood", slug: "n-hollywood", province: "CA", listing_count: 156 },
  { name: "Napa", slug: "napa", province: "CA", listing_count: 325 },
  { name: "National City", slug: "national-city", province: "CA", listing_count: 13 },
  { name: "Needles", slug: "needles", province: "CA", listing_count: 3 },
  { name: "Nevada City", slug: "nevada-city", province: "CA", listing_count: 69 },
  { name: "Newark", slug: "newark", province: "CA", listing_count: 63 },
  { name: "Newbury Park", slug: "newbury-park", province: "CA", listing_count: 120 },
  { name: "Newcastle", slug: "newcastle", province: "CA", listing_count: 5 },
  { name: "Newhall", slug: "newhall", province: "CA", listing_count: 30 },
  { name: "Newport Beach", slug: "newport-beach", province: "CA", listing_count: 2184 },
  { name: "Newport Coast", slug: "newport-coast", province: "CA", listing_count: 40 },
  { name: "Nicasio", slug: "nicasio", province: "CA", listing_count: 9 },
  { name: "Nipomo", slug: "nipomo", province: "CA", listing_count: 33 },
  { name: "Norco", slug: "norco", province: "CA", listing_count: 20 },
  { name: "North Hills", slug: "north-hills", province: "CA", listing_count: 21 },
  { name: "North Hollywood", slug: "north-hollywood", province: "CA", listing_count: 43 },
  { name: "Northridge", slug: "northridge", province: "CA", listing_count: 130 },
  { name: "Norwalk", slug: "norwalk", province: "CA", listing_count: 75 },
  { name: "Novato", slug: "novato", province: "CA", listing_count: 256 },
  { name: "Oak Park", slug: "oak-park", province: "CA", listing_count: 46 },
  { name: "Oak View", slug: "oak-view", province: "CA", listing_count: 6 },
  { name: "Oakdale", slug: "oakdale", province: "CA", listing_count: 11 },
  { name: "Oakhurst", slug: "oakhurst", province: "CA", listing_count: 11 },
  { name: "Oakland", slug: "oakland", province: "CA", listing_count: 3909 },
  { name: "Oakley", slug: "oakley", province: "CA", listing_count: 8 },
  { name: "Occidental", slug: "occidental", province: "CA", listing_count: 4 },
  { name: "Oceano", slug: "oceano", province: "CA", listing_count: 4 },
  { name: "Oceanside", slug: "oceanside", province: "CA", listing_count: 200 },
  { name: "Ojai", slug: "ojai", province: "CA", listing_count: 59 },
  { name: "Olympic Vly", slug: "olympic-vly", province: "CA", listing_count: 8 },
  { name: "Ontario", slug: "ontario", province: "CA", listing_count: 352 },
  { name: "Orange", slug: "orange", province: "CA", listing_count: 733 },
  { name: "Orangevale", slug: "orangevale", province: "CA", listing_count: 25 },
  { name: "Orcutt", slug: "orcutt", province: "CA", listing_count: 4 },
  { name: "Orinda", slug: "orinda", province: "CA", listing_count: 194 },
  { name: "Oroville", slug: "oroville", province: "CA", listing_count: 56 },
  { name: "Oxnard", slug: "oxnard", province: "CA", listing_count: 211 },
  { name: "Pacheco", slug: "pacheco", province: "CA", listing_count: 6 },
  { name: "Pacific Grove", slug: "pacific-grove", province: "CA", listing_count: 42 },
  { name: "Pacific Palisades", slug: "pacific-palisades", province: "CA", listing_count: 17 },
  { name: "Pacific Plsds", slug: "pacific-plsds", province: "CA", listing_count: 117 },
  { name: "Pacifica", slug: "pacifica", province: "CA", listing_count: 62 },
  { name: "Pacoima", slug: "pacoima", province: "CA", listing_count: 52 },
  { name: "Palm Desert", slug: "palm-desert", province: "CA", listing_count: 219 },
  { name: "Palm Springs", slug: "palm-springs", province: "CA", listing_count: 159 },
  { name: "Palmdale", slug: "palmdale", province: "CA", listing_count: 49 },
  { name: "Palo Alto", slug: "palo-alto", province: "CA", listing_count: 2221 },
  { name: "Palo Cedro", slug: "palo-cedro", province: "CA", listing_count: 7 },
  { name: "Palos Verdes", slug: "palos-verdes", province: "CA", listing_count: 3 },
  { name: "Palos Verdes Estates", slug: "palos-verdes-estates", province: "CA", listing_count: 13 },
  { name: "Palos Verdes Peninsula", slug: "palos-verdes-peninsula", province: "CA", listing_count: 6 },
  { name: "Panorama City", slug: "panorama-city", province: "CA", listing_count: 15 },
  { name: "Paradise", slug: "paradise", province: "CA", listing_count: 6 },
  { name: "Paramount", slug: "paramount", province: "CA", listing_count: 10 },
  { name: "Pasadena", slug: "pasadena", province: "CA", listing_count: 2054 },
  { name: "Paso Robles", slug: "paso-robles", province: "CA", listing_count: 43 },
  { name: "Patterson", slug: "patterson", province: "CA", listing_count: 5 },
  { name: "Pebble Beach", slug: "pebble-beach", province: "CA", listing_count: 16 },
  { name: "Penn Valley", slug: "penn-valley", province: "CA", listing_count: 12 },
  { name: "Penngrove", slug: "penngrove", province: "CA", listing_count: 6 },
  { name: "Perris", slug: "perris", province: "CA", listing_count: 10 },
  { name: "Pescadero", slug: "pescadero", province: "CA", listing_count: 4 },
  { name: "Petaluma", slug: "petaluma", province: "CA", listing_count: 171 },
  { name: "Pico Rivera", slug: "pico-rivera", province: "CA", listing_count: 13 },
  { name: "Piedmont", slug: "piedmont", province: "CA", listing_count: 93 },
  { name: "Pine Valley", slug: "pine-valley", province: "CA", listing_count: 3 },
  { name: "Pinole", slug: "pinole", province: "CA", listing_count: 16 },
  { name: "Pismo Beach", slug: "pismo-beach", province: "CA", listing_count: 34 },
  { name: "Pittsburg", slug: "pittsburg", province: "CA", listing_count: 29 },
  { name: "Placentia", slug: "placentia", province: "CA", listing_count: 61 },
  { name: "Placerville", slug: "placerville", province: "CA", listing_count: 90 },
  { name: "Playa Del Rey", slug: "playa-del-rey", province: "CA", listing_count: 64 },
  { name: "Playa Vista", slug: "playa-vista", province: "CA", listing_count: 117 },
  { name: "Pleasant Hill", slug: "pleasant-hill", province: "CA", listing_count: 178 },
  { name: "Pleasanton", slug: "pleasanton", province: "CA", listing_count: 444 },
  { name: "Pls Vrds Est", slug: "pls-vrds-est", province: "CA", listing_count: 71 },
  { name: "Pls Vrds Pnsl", slug: "pls-vrds-pnsl", province: "CA", listing_count: 48 },
  { name: "Point Arena", slug: "point-arena", province: "CA", listing_count: 3 },
  { name: "Pollock Pines", slug: "pollock-pines", province: "CA", listing_count: 6 },
  { name: "Pomona", slug: "pomona", province: "CA", listing_count: 117 },
  { name: "Port Hueneme", slug: "port-hueneme", province: "CA", listing_count: 18 },
  { name: "Porter Ranch", slug: "porter-ranch", province: "CA", listing_count: 80 },
  { name: "Porterville", slug: "porterville", province: "CA", listing_count: 21 },
  { name: "Portola Valley", slug: "portola-valley", province: "CA", listing_count: 15 },
  { name: "Portola Vally", slug: "portola-vally", province: "CA", listing_count: 41 },
  { name: "Poway", slug: "poway", province: "CA", listing_count: 108 },
  { name: "Presidio", slug: "presidio", province: "CA", listing_count: 4 },
  { name: "Quincy", slug: "quincy", province: "CA", listing_count: 16 },
  { name: "Ramona", slug: "ramona", province: "CA", listing_count: 24 },
  { name: "Rancho Cordova", slug: "rancho-cordova", province: "CA", listing_count: 83 },
  { name: "Rancho Cucamonga", slug: "rancho-cucamonga", province: "CA", listing_count: 93 },
  { name: "Rancho Mirage", slug: "rancho-mirage", province: "CA", listing_count: 113 },
  { name: "Rancho Mission Viejo", slug: "rancho-mission-viejo", province: "CA", listing_count: 9 },
  { name: "Rancho Murieta", slug: "rancho-murieta", province: "CA", listing_count: 4 },
  { name: "Rancho Palos Verdes", slug: "rancho-palos-verdes", province: "CA", listing_count: 15 },
  { name: "Rancho Santa Fe", slug: "rancho-santa-fe", province: "CA", listing_count: 191 },
  { name: "Rancho Santa Margarita", slug: "rancho-santa-margarita", province: "CA", listing_count: 26 },
  { name: "Rancho Sta Marg", slug: "rancho-sta-marg", province: "CA", listing_count: 86 },
  { name: "Rch Cucamonga", slug: "rch-cucamonga", province: "CA", listing_count: 346 },
  { name: "Rch Palos Vrd", slug: "rch-palos-vrd", province: "CA", listing_count: 98 },
  { name: "Red Bluff", slug: "red-bluff", province: "CA", listing_count: 35 },
  { name: "Redding", slug: "redding", province: "CA", listing_count: 241 },
  { name: "Redlands", slug: "redlands", province: "CA", listing_count: 184 },
  { name: "Redondo Beach", slug: "redondo-beach", province: "CA", listing_count: 317 },
  { name: "Redwood City", slug: "redwood-city", province: "CA", listing_count: 1220 },
  { name: "Redwood Shores", slug: "redwood-shores", province: "CA", listing_count: 46 },
  { name: "Redwood Vly", slug: "redwood-vly", province: "CA", listing_count: 3 },
  { name: "Reedley", slug: "reedley", province: "CA", listing_count: 3 },
  { name: "Rescue", slug: "rescue", province: "CA", listing_count: 6 },
  { name: "Reseda", slug: "reseda", province: "CA", listing_count: 28 },
  { name: "Rialto", slug: "rialto", province: "CA", listing_count: 11 },
  { name: "Richmond", slug: "richmond", province: "CA", listing_count: 125 },
  { name: "Ridgecrest", slug: "ridgecrest", province: "CA", listing_count: 17 },
  { name: "Rio Linda", slug: "rio-linda", province: "CA", listing_count: 5 },
  { name: "Rio Vista", slug: "rio-vista", province: "CA", listing_count: 5 },
  { name: "Ripon", slug: "ripon", province: "CA", listing_count: 17 },
  { name: "Riverside", slug: "riverside", province: "CA", listing_count: 1160 },
  { name: "Rllng Hills Est", slug: "rllng-hills-est", province: "CA", listing_count: 69 },
  { name: "Rmv", slug: "rmv", province: "CA", listing_count: 16 },
  { name: "Rnch Cascades", slug: "rnch-cascades", province: "CA", listing_count: 4 },
  { name: "Rncho Cordova", slug: "rncho-cordova", province: "CA", listing_count: 141 },
  { name: "Rncho Murieta", slug: "rncho-murieta", province: "CA", listing_count: 3 },
  { name: "Rocklin", slug: "rocklin", province: "CA", listing_count: 191 },
  { name: "Rodeo", slug: "rodeo", province: "CA", listing_count: 6 },
  { name: "Rohnert Park", slug: "rohnert-park", province: "CA", listing_count: 25 },
  { name: "Rolling Hills", slug: "rolling-hills", province: "CA", listing_count: 10 },
  { name: "Rolling Hills Estates", slug: "rolling-hills-estates", province: "CA", listing_count: 15 },
  { name: "Rosemead", slug: "rosemead", province: "CA", listing_count: 132 },
  { name: "Roseville", slug: "roseville", province: "CA", listing_count: 733 },
  { name: "Ross", slug: "ross", province: "CA", listing_count: 25 },
  { name: "Rowland Heights", slug: "rowland-heights", province: "CA", listing_count: 3 },
  { name: "Rowland Hghts", slug: "rowland-hghts", province: "CA", listing_count: 16 },
  { name: "Royal Oaks", slug: "royal-oaks", province: "CA", listing_count: 3 },
  { name: "Running Springs", slug: "running-springs", province: "CA", listing_count: 4 },
  { name: "Rutherford", slug: "rutherford", province: "CA", listing_count: 3 },
  { name: "S El Monte", slug: "s-el-monte", province: "CA", listing_count: 4 },
  { name: "S Lake Tahoe", slug: "s-lake-tahoe", province: "CA", listing_count: 54 },
  { name: "S Pasadena", slug: "s-pasadena", province: "CA", listing_count: 158 },
  { name: "S San Fran", slug: "s-san-fran", province: "CA", listing_count: 278 },
  { name: "S San Francisco", slug: "s-san-francisco", province: "CA", listing_count: 5 },
  { name: "Sacramento", slug: "sacramento", province: "CA", listing_count: 7304 },
  { name: "Saint Helena", slug: "saint-helena", province: "CA", listing_count: 35 },
  { name: "Salida", slug: "salida", province: "CA", listing_count: 4 },
  { name: "Salinas", slug: "salinas", province: "CA", listing_count: 329 },
  { name: "San Andreas", slug: "san-andreas", province: "CA", listing_count: 19 },
  { name: "San Anselmo", slug: "san-anselmo", province: "CA", listing_count: 83 },
  { name: "San Bernardino", slug: "san-bernardino", province: "CA", listing_count: 206 },
  { name: "San Bernrdno", slug: "san-bernrdno", province: "CA", listing_count: 349 },
  { name: "San Bruno", slug: "san-bruno", province: "CA", listing_count: 65 },
  { name: "San Carlos", slug: "san-carlos", province: "CA", listing_count: 166 },
  { name: "San Clemente", slug: "san-clemente", province: "CA", listing_count: 254 },
  { name: "San Diego", slug: "san-diego", province: "CA", listing_count: 11345 },
  { name: "San Dimas", slug: "san-dimas", province: "CA", listing_count: 54 },
  { name: "San Fernando", slug: "san-fernando", province: "CA", listing_count: 35 },
  { name: "San Francisco", slug: "san-francisco", province: "CA", listing_count: 16486 },
  { name: "San Gabriel", slug: "san-gabriel", province: "CA", listing_count: 74 },
  { name: "San Jacinto", slug: "san-jacinto", province: "CA", listing_count: 5 },
  { name: "San Jose", slug: "san-jose", province: "CA", listing_count: 3368 },
  { name: "San Juan Capistrano", slug: "san-juan-capistrano", province: "CA", listing_count: 139 },
  { name: "San Leandro", slug: "san-leandro", province: "CA", listing_count: 109 },
  { name: "San Lorenzo", slug: "san-lorenzo", province: "CA", listing_count: 7 },
  { name: "San Luis Obispo", slug: "san-luis-obispo", province: "CA", listing_count: 394 },
  { name: "San Luis Rey", slug: "san-luis-rey", province: "CA", listing_count: 3 },
  { name: "San Marcos", slug: "san-marcos", province: "CA", listing_count: 163 },
  { name: "San Marino", slug: "san-marino", province: "CA", listing_count: 142 },
  { name: "San Martin", slug: "san-martin", province: "CA", listing_count: 12 },
  { name: "San Mateo", slug: "san-mateo", province: "CA", listing_count: 667 },
  { name: "San Pablo", slug: "san-pablo", province: "CA", listing_count: 22 },
  { name: "San Pedro", slug: "san-pedro", province: "CA", listing_count: 104 },
  { name: "San Quentin", slug: "san-quentin", province: "CA", listing_count: 3 },
  { name: "San Rafael", slug: "san-rafael", province: "CA", listing_count: 728 },
  { name: "San Ramon", slug: "san-ramon", province: "CA", listing_count: 295 },
  { name: "San Ysidro", slug: "san-ysidro", province: "CA", listing_count: 10 },
  { name: "Sanger", slug: "sanger", province: "CA", listing_count: 8 },
  { name: "Santa Ana", slug: "santa-ana", province: "CA", listing_count: 1880 },
  { name: "Santa Barbara", slug: "santa-barbara", province: "CA", listing_count: 974 },
  { name: "Santa Clara", slug: "santa-clara", province: "CA", listing_count: 573 },
  { name: "Santa Clarita", slug: "santa-clarita", province: "CA", listing_count: 76 },
  { name: "Santa Cruz", slug: "santa-cruz", province: "CA", listing_count: 344 },
  { name: "Santa Fe Springs", slug: "santa-fe-springs", province: "CA", listing_count: 55 },
  { name: "Santa Maria", slug: "santa-maria", province: "CA", listing_count: 149 },
  { name: "Santa Monica", slug: "santa-monica", province: "CA", listing_count: 1822 },
  { name: "Santa Paula", slug: "santa-paula", province: "CA", listing_count: 16 },
  { name: "Santa Rosa", slug: "santa-rosa", province: "CA", listing_count: 837 },
  { name: "Santa Rosa Va", slug: "santa-rosa-va", province: "CA", listing_count: 6 },
  { name: "Santa Ynez", slug: "santa-ynez", province: "CA", listing_count: 18 },
  { name: "Santee", slug: "santee", province: "CA", listing_count: 16 },
  { name: "Saratoga", slug: "saratoga", province: "CA", listing_count: 102 },
  { name: "Sausalito", slug: "sausalito", province: "CA", listing_count: 146 },
  { name: "Scotts Valley", slug: "scotts-valley", province: "CA", listing_count: 39 },
  { name: "Seal Beach", slug: "seal-beach", province: "CA", listing_count: 157 },
  { name: "Seaside", slug: "seaside", province: "CA", listing_count: 15 },
  { name: "Sebastopol", slug: "sebastopol", province: "CA", listing_count: 89 },
  { name: "Selma", slug: "selma", province: "CA", listing_count: 5 },
  { name: "Shafter", slug: "shafter", province: "CA", listing_count: 9 },
  { name: "Shasta Lake", slug: "shasta-lake", province: "CA", listing_count: 3 },
  { name: "Shaver Lake", slug: "shaver-lake", province: "CA", listing_count: 3 },
  { name: "Shell Beach", slug: "shell-beach", province: "CA", listing_count: 5 },
  { name: "Sherman Oaks", slug: "sherman-oaks", province: "CA", listing_count: 880 },
  { name: "Sherwood Frst", slug: "sherwood-frst", province: "CA", listing_count: 6 },
  { name: "Shingle Springs", slug: "shingle-springs", province: "CA", listing_count: 27 },
  { name: "Shingletown", slug: "shingletown", province: "CA", listing_count: 4 },
  { name: "Sierra Madre", slug: "sierra-madre", province: "CA", listing_count: 55 },
  { name: "Signal Hill", slug: "signal-hill", province: "CA", listing_count: 19 },
  { name: "Silverado", slug: "silverado", province: "CA", listing_count: 7 },
  { name: "Simi Valley", slug: "simi-valley", province: "CA", listing_count: 171 },
  { name: "Sloughhouse", slug: "sloughhouse", province: "CA", listing_count: 6 },
  { name: "Solana Beach", slug: "solana-beach", province: "CA", listing_count: 186 },
  { name: "Solvang", slug: "solvang", province: "CA", listing_count: 30 },
  { name: "Somis", slug: "somis", province: "CA", listing_count: 11 },
  { name: "Sonoma", slug: "sonoma", province: "CA", listing_count: 76 },
  { name: "Sonora", slug: "sonora", province: "CA", listing_count: 51 },
  { name: "Soquel", slug: "soquel", province: "CA", listing_count: 31 },
  { name: "South Gate", slug: "south-gate", province: "CA", listing_count: 16 },
  { name: "South Pasadena", slug: "south-pasadena", province: "CA", listing_count: 22 },
  { name: "South San Francisco", slug: "south-san-francisco", province: "CA", listing_count: 59 },
  { name: "Spring Valley", slug: "spring-valley", province: "CA", listing_count: 29 },
  { name: "Stanford", slug: "stanford", province: "CA", listing_count: 105 },
  { name: "Stanton", slug: "stanton", province: "CA", listing_count: 9 },
  { name: "Stevenson Ranch", slug: "stevenson-ranch", province: "CA", listing_count: 9 },
  { name: "Stevenson Rnh", slug: "stevenson-rnh", province: "CA", listing_count: 35 },
  { name: "Stinson Beach", slug: "stinson-beach", province: "CA", listing_count: 7 },
  { name: "Stockton", slug: "stockton", province: "CA", listing_count: 501 },
  { name: "Studio City", slug: "studio-city", province: "CA", listing_count: 252 },
  { name: "Suisun City", slug: "suisun-city", province: "CA", listing_count: 19 },
  { name: "Summerland", slug: "summerland", province: "CA", listing_count: 7 },
  { name: "Sun Valley", slug: "sun-valley", province: "CA", listing_count: 12 },
  { name: "Sunland", slug: "sunland", province: "CA", listing_count: 15 },
  { name: "Sunnyvale", slug: "sunnyvale", province: "CA", listing_count: 353 },
  { name: "Sunset Beach", slug: "sunset-beach", province: "CA", listing_count: 8 },
  { name: "Susanville", slug: "susanville", province: "CA", listing_count: 13 },
  { name: "Sutter Creek", slug: "sutter-creek", province: "CA", listing_count: 9 },
  { name: "Sylmar", slug: "sylmar", province: "CA", listing_count: 21 },
  { name: "Tahoe City", slug: "tahoe-city", province: "CA", listing_count: 16 },
  { name: "Tarzana", slug: "tarzana", province: "CA", listing_count: 211 },
  { name: "Tehachapi", slug: "tehachapi", province: "CA", listing_count: 13 },
  { name: "Temecula", slug: "temecula", province: "CA", listing_count: 232 },
  { name: "Temple City", slug: "temple-city", province: "CA", listing_count: 21 },
  { name: "Templeton", slug: "templeton", province: "CA", listing_count: 9 },
  { name: "The Sea Ranch", slug: "the-sea-ranch", province: "CA", listing_count: 5 },
  { name: "Thermal", slug: "thermal", province: "CA", listing_count: 5 },
  { name: "Thousand Oaks", slug: "thousand-oaks", province: "CA", listing_count: 249 },
  { name: "Three Rivers", slug: "three-rivers", province: "CA", listing_count: 6 },
  { name: "Tiburon", slug: "tiburon", province: "CA", listing_count: 18 },
  { name: "Toluca Lake", slug: "toluca-lake", province: "CA", listing_count: 21 },
  { name: "Topanga", slug: "topanga", province: "CA", listing_count: 16 },
  { name: "Torrance", slug: "torrance", province: "CA", listing_count: 819 },
  { name: "Trabuco Canyon", slug: "trabuco-canyon", province: "CA", listing_count: 6 },
  { name: "Trabuco Cyn", slug: "trabuco-cyn", province: "CA", listing_count: 45 },
  { name: "Tracy", slug: "tracy", province: "CA", listing_count: 34 },
  { name: "Travis Afb", slug: "travis-afb", province: "CA", listing_count: 3 },
  { name: "Trinidad", slug: "trinidad", province: "CA", listing_count: 4 },
  { name: "Truckee", slug: "truckee", province: "CA", listing_count: 79 },
  { name: "Tujunga", slug: "tujunga", province: "CA", listing_count: 18 },
  { name: "Tulare", slug: "tulare", province: "CA", listing_count: 16 },
  { name: "Turlock", slug: "turlock", province: "CA", listing_count: 45 },
  { name: "Tustin", slug: "tustin", province: "CA", listing_count: 425 },
  { name: "Twentynin Plm", slug: "twentynin-plm", province: "CA", listing_count: 5 },
  { name: "Ukiah", slug: "ukiah", province: "CA", listing_count: 82 },
  { name: "Union City", slug: "union-city", province: "CA", listing_count: 35 },
  { name: "Universal City", slug: "universal-city", province: "CA", listing_count: 168 },
  { name: "Upland", slug: "upland", province: "CA", listing_count: 157 },
  { name: "Vacaville", slug: "vacaville", province: "CA", listing_count: 62 },
  { name: "Valencia", slug: "valencia", province: "CA", listing_count: 257 },
  { name: "Vallejo", slug: "vallejo", province: "CA", listing_count: 101 },
  { name: "Valley Center", slug: "valley-center", province: "CA", listing_count: 17 },
  { name: "Valley Springs", slug: "valley-springs", province: "CA", listing_count: 3 },
  { name: "Valley Village", slug: "valley-village", province: "CA", listing_count: 91 },
  { name: "Van Nuys", slug: "van-nuys", province: "CA", listing_count: 401 },
  { name: "Venice", slug: "venice", province: "CA", listing_count: 134 },
  { name: "Ventura", slug: "ventura", province: "CA", listing_count: 677 },
  { name: "Verdugo City", slug: "verdugo-city", province: "CA", listing_count: 12 },
  { name: "Vernon", slug: "vernon", province: "CA", listing_count: 16 },
  { name: "Victorville", slug: "victorville", province: "CA", listing_count: 104 },
  { name: "View Park", slug: "view-park", province: "CA", listing_count: 12 },
  { name: "Villa Park", slug: "villa-park", province: "CA", listing_count: 27 },
  { name: "Visalia", slug: "visalia", province: "CA", listing_count: 258 },
  { name: "Vista", slug: "vista", province: "CA", listing_count: 252 },
  { name: "Walnut", slug: "walnut", province: "CA", listing_count: 52 },
  { name: "Walnut Creek", slug: "walnut-creek", province: "CA", listing_count: 1393 },
  { name: "Watsonville", slug: "watsonville", province: "CA", listing_count: 46 },
  { name: "Weaverville", slug: "weaverville", province: "CA", listing_count: 13 },
  { name: "Weed", slug: "weed", province: "CA", listing_count: 5 },
  { name: "West Covina", slug: "west-covina", province: "CA", listing_count: 143 },
  { name: "West Hills", slug: "west-hills", province: "CA", listing_count: 121 },
  { name: "West Hollywood", slug: "west-hollywood", province: "CA", listing_count: 446 },
  { name: "West Sacramento", slug: "west-sacramento", province: "CA", listing_count: 140 },
  { name: "Westlake Village", slug: "westlake-village", province: "CA", listing_count: 777 },
  { name: "Westminster", slug: "westminster", province: "CA", listing_count: 104 },
  { name: "Westwood", slug: "westwood", province: "CA", listing_count: 3 },
  { name: "Whittier", slug: "whittier", province: "CA", listing_count: 169 },
  { name: "Wildomar", slug: "wildomar", province: "CA", listing_count: 16 },
  { name: "Willits", slug: "willits", province: "CA", listing_count: 3 },
  { name: "Willows", slug: "willows", province: "CA", listing_count: 9 },
  { name: "Wilmington", slug: "wilmington", province: "CA", listing_count: 4 },
  { name: "Wilton", slug: "wilton", province: "CA", listing_count: 9 },
  { name: "Winchester", slug: "winchester", province: "CA", listing_count: 5 },
  { name: "Windsor", slug: "windsor", province: "CA", listing_count: 39 },
  { name: "Winnetka", slug: "winnetka", province: "CA", listing_count: 20 },
  { name: "Winters", slug: "winters", province: "CA", listing_count: 10 },
  { name: "Woodacre", slug: "woodacre", province: "CA", listing_count: 4 },
  { name: "Woodbridge", slug: "woodbridge", province: "CA", listing_count: 11 },
  { name: "Woodland", slug: "woodland", province: "CA", listing_count: 147 },
  { name: "Woodland Hills", slug: "woodland-hills", province: "CA", listing_count: 1355 },
  { name: "Woodside", slug: "woodside", province: "CA", listing_count: 36 },
  { name: "Wrightwood", slug: "wrightwood", province: "CA", listing_count: 4 },
  { name: "Yorba Linda", slug: "yorba-linda", province: "CA", listing_count: 125 },
  { name: "Yorkville", slug: "yorkville", province: "CA", listing_count: 3 },
  { name: "Yountville", slug: "yountville", province: "CA", listing_count: 4 },
  { name: "Yreka", slug: "yreka", province: "CA", listing_count: 36 },
  { name: "Yuba City", slug: "yuba-city", province: "CA", listing_count: 68 },
  { name: "Yucaipa", slug: "yucaipa", province: "CA", listing_count: 18 },
  { name: "Yucca Valley", slug: "yucca-valley", province: "CA", listing_count: 12 },
  { name: "Alachua", slug: "alachua", province: "FL", listing_count: 28 },
  { name: "Altamonte Springs", slug: "altamonte-springs", province: "FL", listing_count: 210 },
  { name: "Alva", slug: "alva", province: "FL", listing_count: 8 },
  { name: "Amelia Island", slug: "amelia-island", province: "FL", listing_count: 11 },
  { name: "Apalachicola", slug: "apalachicola", province: "FL", listing_count: 10 },
  { name: "Apollo Beach", slug: "apollo-beach", province: "FL", listing_count: 31 },
  { name: "Apopka", slug: "apopka", province: "FL", listing_count: 83 },
  { name: "Arcadia", slug: "arcadia", province: "FL", listing_count: 20 },
  { name: "Archer", slug: "archer", province: "FL", listing_count: 4 },
  { name: "Atlantic Beach", slug: "atlantic-beach", province: "FL", listing_count: 74 },
  { name: "Atlantis", slug: "atlantis", province: "FL", listing_count: 9 },
  { name: "Auburndale", slug: "auburndale", province: "FL", listing_count: 13 },
  { name: "Ave Maria", slug: "ave-maria", province: "FL", listing_count: 8 },
  { name: "Aventura", slug: "aventura", province: "FL", listing_count: 270 },
  { name: "Avon Park", slug: "avon-park", province: "FL", listing_count: 4 },
  { name: "Bal Harbour", slug: "bal-harbour", province: "FL", listing_count: 13 },
  { name: "Bartow", slug: "bartow", province: "FL", listing_count: 257 },
  { name: "Bay Harbor Islands", slug: "bay-harbor-islands", province: "FL", listing_count: 30 },
  { name: "Bell", slug: "bell", province: "FL", listing_count: 3 },
  { name: "Belle Glade", slug: "belle-glade", province: "FL", listing_count: 6 },
  { name: "Belle Isle", slug: "belle-isle", province: "FL", listing_count: 9 },
  { name: "Belleair", slug: "belleair", province: "FL", listing_count: 5 },
  { name: "Belleair Beach", slug: "belleair-beach", province: "FL", listing_count: 6 },
  { name: "Belleair Bluffs", slug: "belleair-bluffs", province: "FL", listing_count: 8 },
  { name: "Belleview", slug: "belleview", province: "FL", listing_count: 3 },
  { name: "Beverly Hills", slug: "beverly-hills", province: "FL", listing_count: 4 },
  { name: "Big Pine Key", slug: "big-pine-key", province: "FL", listing_count: 5 },
  { name: "Biscayne Park", slug: "biscayne-park", province: "FL", listing_count: 5 },
  { name: "Blountstown", slug: "blountstown", province: "FL", listing_count: 3 },
  { name: "Boca Raton", slug: "boca-raton", province: "FL", listing_count: 2345 },
  { name: "Bokeelia", slug: "bokeelia", province: "FL", listing_count: 6 },
  { name: "Bonifay", slug: "bonifay", province: "FL", listing_count: 5 },
  { name: "Bonita Springs", slug: "bonita-springs", province: "FL", listing_count: 99 },
  { name: "Boynton Beach", slug: "boynton-beach", province: "FL", listing_count: 308 },
  { name: "Bradenton", slug: "bradenton", province: "FL", listing_count: 468 },
  { name: "Brandon", slug: "brandon", province: "FL", listing_count: 174 },
  { name: "Branford", slug: "branford", province: "FL", listing_count: 3 },
  { name: "Bronson", slug: "bronson", province: "FL", listing_count: 7 },
  { name: "Brooksville", slug: "brooksville", province: "FL", listing_count: 109 },
  { name: "Bunnell", slug: "bunnell", province: "FL", listing_count: 20 },
  { name: "Bushnell", slug: "bushnell", province: "FL", listing_count: 23 },
  { name: "Callahan", slug: "callahan", province: "FL", listing_count: 4 },
  { name: "Cantonment", slug: "cantonment", province: "FL", listing_count: 12 },
  { name: "Cape Canaveral", slug: "cape-canaveral", province: "FL", listing_count: 16 },
  { name: "Cape Coral", slug: "cape-coral", province: "FL", listing_count: 149 },
  { name: "Casselberry", slug: "casselberry", province: "FL", listing_count: 64 },
  { name: "Cedar Key", slug: "cedar-key", province: "FL", listing_count: 6 },
  { name: "Celebration", slug: "celebration", province: "FL", listing_count: 35 },
  { name: "Chattahoochee", slug: "chattahoochee", province: "FL", listing_count: 4 },
  { name: "Chiefland", slug: "chiefland", province: "FL", listing_count: 7 },
  { name: "Chipley", slug: "chipley", province: "FL", listing_count: 11 },
  { name: "Chuluota", slug: "chuluota", province: "FL", listing_count: 10 },
  { name: "Clarcona", slug: "clarcona", province: "FL", listing_count: 4 },
  { name: "Clearwater", slug: "clearwater", province: "FL", listing_count: 902 },
  { name: "Clearwater Beach", slug: "clearwater-beach", province: "FL", listing_count: 6 },
  { name: "Clermont", slug: "clermont", province: "FL", listing_count: 99 },
  { name: "Clewiston", slug: "clewiston", province: "FL", listing_count: 6 },
  { name: "Cocoa", slug: "cocoa", province: "FL", listing_count: 67 },
  { name: "Cocoa Beach", slug: "cocoa-beach", province: "FL", listing_count: 30 },
  { name: "Coconut Creek", slug: "coconut-creek", province: "FL", listing_count: 69 },
  { name: "Coconut Grove", slug: "coconut-grove", province: "FL", listing_count: 96 },
  { name: "Cooper City", slug: "cooper-city", province: "FL", listing_count: 44 },
  { name: "Coral Gables", slug: "coral-gables", province: "FL", listing_count: 2401 },
  { name: "Coral Springs", slug: "coral-springs", province: "FL", listing_count: 441 },
  { name: "Crawfordville", slug: "crawfordville", province: "FL", listing_count: 20 },
  { name: "Crestview", slug: "crestview", province: "FL", listing_count: 53 },
  { name: "Cross City", slug: "cross-city", province: "FL", listing_count: 3 },
  { name: "Crystal Beach", slug: "crystal-beach", province: "FL", listing_count: 5 },
  { name: "Crystal River", slug: "crystal-river", province: "FL", listing_count: 18 },
  { name: "Cutler Bay", slug: "cutler-bay", province: "FL", listing_count: 34 },
  { name: "Dade City", slug: "dade-city", province: "FL", listing_count: 60 },
  { name: "Dania", slug: "dania", province: "FL", listing_count: 15 },
  { name: "Dania Beach", slug: "dania-beach", province: "FL", listing_count: 38 },
  { name: "Davenport", slug: "davenport", province: "FL", listing_count: 20 },
  { name: "Davie", slug: "davie", province: "FL", listing_count: 324 },
  { name: "Daytona Beach", slug: "daytona-beach", province: "FL", listing_count: 416 },
  { name: "Daytona Beach Shores", slug: "daytona-beach-shores", province: "FL", listing_count: 7 },
  { name: "De Leon Springs", slug: "de-leon-springs", province: "FL", listing_count: 5 },
  { name: "Debary", slug: "debary", province: "FL", listing_count: 14 },
  { name: "Deerfield Beach", slug: "deerfield-beach", province: "FL", listing_count: 256 },
  { name: "Defuniak Springs", slug: "defuniak-springs", province: "FL", listing_count: 26 },
  { name: "Deland", slug: "deland", province: "FL", listing_count: 200 },
  { name: "Delray Beach", slug: "delray-beach", province: "FL", listing_count: 386 },
  { name: "Deltona", slug: "deltona", province: "FL", listing_count: 12 },
  { name: "Destin", slug: "destin", province: "FL", listing_count: 60 },
  { name: "Doral", slug: "doral", province: "FL", listing_count: 239 },
  { name: "Dover", slug: "dover", province: "FL", listing_count: 5 },
  { name: "Dunedin", slug: "dunedin", province: "FL", listing_count: 73 },
  { name: "Dunnellon", slug: "dunnellon", province: "FL", listing_count: 9 },
  { name: "Eagle Lake", slug: "eagle-lake", province: "FL", listing_count: 3 },
  { name: "Earleton", slug: "earleton", province: "FL", listing_count: 3 },
  { name: "Eaton Park", slug: "eaton-park", province: "FL", listing_count: 3 },
  { name: "Edgewater", slug: "edgewater", province: "FL", listing_count: 8 },
  { name: "Edgewood", slug: "edgewood", province: "FL", listing_count: 3 },
  { name: "Eglin Afb", slug: "eglin-afb", province: "FL", listing_count: 4 },
  { name: "El Portal", slug: "el-portal", province: "FL", listing_count: 5 },
  { name: "Ellenton", slug: "ellenton", province: "FL", listing_count: 9 },
  { name: "Englewood", slug: "englewood", province: "FL", listing_count: 21 },
  { name: "Estero", slug: "estero", province: "FL", listing_count: 55 },
  { name: "Eustis", slug: "eustis", province: "FL", listing_count: 28 },
  { name: "Fanning Springs", slug: "fanning-springs", province: "FL", listing_count: 3 },
  { name: "Fern Park", slug: "fern-park", province: "FL", listing_count: 6 },
  { name: "Fernandina Beach", slug: "fernandina-beach", province: "FL", listing_count: 92 },
  { name: "Flagler Beach", slug: "flagler-beach", province: "FL", listing_count: 25 },
  { name: "Fleming Island", slug: "fleming-island", province: "FL", listing_count: 60 },
  { name: "Florida City", slug: "florida-city", province: "FL", listing_count: 4 },
  { name: "Fort Lauderdale", slug: "fort-lauderdale", province: "FL", listing_count: 4498 },
  { name: "Fort Meade", slug: "fort-meade", province: "FL", listing_count: 4 },
  { name: "Fort Myers", slug: "fort-myers", province: "FL", listing_count: 985 },
  { name: "Fort Myers Beach", slug: "fort-myers-beach", province: "FL", listing_count: 4 },
  { name: "Fort Pierce", slug: "fort-pierce", province: "FL", listing_count: 202 },
  { name: "Fort Walton Beach", slug: "fort-walton-beach", province: "FL", listing_count: 102 },
  { name: "Fort White", slug: "fort-white", province: "FL", listing_count: 3 },
  { name: "Freeport", slug: "freeport", province: "FL", listing_count: 13 },
  { name: "Frostproof", slug: "frostproof", province: "FL", listing_count: 3 },
  { name: "Fruitland Park", slug: "fruitland-park", province: "FL", listing_count: 5 },
  { name: "Gainesville", slug: "gainesville", province: "FL", listing_count: 798 },
  { name: "Geneva", slug: "geneva", province: "FL", listing_count: 4 },
  { name: "Gibsonton", slug: "gibsonton", province: "FL", listing_count: 3 },
  { name: "Golden Beach", slug: "golden-beach", province: "FL", listing_count: 4 },
  { name: "Goldenrod", slug: "goldenrod", province: "FL", listing_count: 5 },
  { name: "Gotha", slug: "gotha", province: "FL", listing_count: 11 },
  { name: "Graceville", slug: "graceville", province: "FL", listing_count: 4 },
  { name: "Green Cove Springs", slug: "green-cove-springs", province: "FL", listing_count: 69 },
  { name: "Greenacres", slug: "greenacres", province: "FL", listing_count: 32 },
  { name: "Groveland", slug: "groveland", province: "FL", listing_count: 19 },
  { name: "Gulf Breeze", slug: "gulf-breeze", province: "FL", listing_count: 50 },
  { name: "Gulfport", slug: "gulfport", province: "FL", listing_count: 35 },
  { name: "Haines City", slug: "haines-city", province: "FL", listing_count: 8 },
  { name: "Hallandale", slug: "hallandale", province: "FL", listing_count: 36 },
  { name: "Hallandale Beach", slug: "hallandale-beach", province: "FL", listing_count: 73 },
  { name: "Havana", slug: "havana", province: "FL", listing_count: 10 },
  { name: "Hawthorne", slug: "hawthorne", province: "FL", listing_count: 4 },
  { name: "Heathrow", slug: "heathrow", province: "FL", listing_count: 14 },
  { name: "Hernando", slug: "hernando", province: "FL", listing_count: 10 },
  { name: "Hernando Beach", slug: "hernando-beach", province: "FL", listing_count: 3 },
  { name: "Hialeah", slug: "hialeah", province: "FL", listing_count: 155 },
  { name: "Hialeah Gardens", slug: "hialeah-gardens", province: "FL", listing_count: 4 },
  { name: "High Springs", slug: "high-springs", province: "FL", listing_count: 17 },
  { name: "Highland Beach", slug: "highland-beach", province: "FL", listing_count: 14 },
  { name: "Highland City", slug: "highland-city", province: "FL", listing_count: 5 },
  { name: "Hillsboro Beach", slug: "hillsboro-beach", province: "FL", listing_count: 6 },
  { name: "Hobe Sound", slug: "hobe-sound", province: "FL", listing_count: 30 },
  { name: "Holiday", slug: "holiday", province: "FL", listing_count: 10 },
  { name: "Holly Hill", slug: "holly-hill", province: "FL", listing_count: 7 },
  { name: "Hollywood", slug: "hollywood", province: "FL", listing_count: 690 },
  { name: "Holmes Beach", slug: "holmes-beach", province: "FL", listing_count: 4 },
  { name: "Homestead", slug: "homestead", province: "FL", listing_count: 53 },
  { name: "Hosford", slug: "hosford", province: "FL", listing_count: 3 },
  { name: "Howey In The Hills", slug: "howey-in-the-hills", province: "FL", listing_count: 5 },
  { name: "Hudson", slug: "hudson", province: "FL", listing_count: 17 },
  { name: "Hutchinson Island", slug: "hutchinson-island", province: "FL", listing_count: 3 },
  { name: "Hypoluxo", slug: "hypoluxo", province: "FL", listing_count: 4 },
  { name: "Immokalee", slug: "immokalee", province: "FL", listing_count: 7 },
  { name: "Indialantic", slug: "indialantic", province: "FL", listing_count: 53 },
  { name: "Indian Harbour Beach", slug: "indian-harbour-beach", province: "FL", listing_count: 26 },
  { name: "Indian Rocks Beach", slug: "indian-rocks-beach", province: "FL", listing_count: 15 },
  { name: "Indiantown", slug: "indiantown", province: "FL", listing_count: 3 },
  { name: "Inlet Beach", slug: "inlet-beach", province: "FL", listing_count: 3 },
  { name: "Inverness", slug: "inverness", province: "FL", listing_count: 65 },
  { name: "Islamorada", slug: "islamorada", province: "FL", listing_count: 19 },
  { name: "Jacksonville", slug: "jacksonville", province: "FL", listing_count: 3485 },
  { name: "Jacksonville Beach", slug: "jacksonville-beach", province: "FL", listing_count: 113 },
  { name: "Jasper", slug: "jasper", province: "FL", listing_count: 4 },
  { name: "Jay", slug: "jay", province: "FL", listing_count: 3 },
  { name: "Jensen Beach", slug: "jensen-beach", province: "FL", listing_count: 23 },
  { name: "Juno Beach", slug: "juno-beach", province: "FL", listing_count: 91 },
  { name: "Jupiter", slug: "jupiter", province: "FL", listing_count: 378 },
  { name: "Kendall", slug: "kendall", province: "FL", listing_count: 5 },
  { name: "Kennedy Space Center", slug: "kennedy-space-center", province: "FL", listing_count: 6 },
  { name: "Kenneth City", slug: "kenneth-city", province: "FL", listing_count: 5 },
  { name: "Key Biscayne", slug: "key-biscayne", province: "FL", listing_count: 87 },
  { name: "Key Largo", slug: "key-largo", province: "FL", listing_count: 29 },
  { name: "Key West", slug: "key-west", province: "FL", listing_count: 125 },
  { name: "Keystone Heights", slug: "keystone-heights", province: "FL", listing_count: 16 },
  { name: "Kissimmee", slug: "kissimmee", province: "FL", listing_count: 208 },
  { name: "Labelle", slug: "labelle", province: "FL", listing_count: 23 },
  { name: "Lady Lake", slug: "lady-lake", province: "FL", listing_count: 8 },
  { name: "Lake Buena Vista", slug: "lake-buena-vista", province: "FL", listing_count: 17 },
  { name: "Lake Butler", slug: "lake-butler", province: "FL", listing_count: 6 },
  { name: "Lake City", slug: "lake-city", province: "FL", listing_count: 83 },
  { name: "Lake Mary", slug: "lake-mary", province: "FL", listing_count: 228 },
  { name: "Lake Monroe", slug: "lake-monroe", province: "FL", listing_count: 6 },
  { name: "Lake Park", slug: "lake-park", province: "FL", listing_count: 3 },
  { name: "Lake Placid", slug: "lake-placid", province: "FL", listing_count: 19 },
  { name: "Lake Wales", slug: "lake-wales", province: "FL", listing_count: 28 },
  { name: "Lake Worth", slug: "lake-worth", province: "FL", listing_count: 170 },
  { name: "Lake Worth Beach", slug: "lake-worth-beach", province: "FL", listing_count: 19 },
  { name: "Lakeland", slug: "lakeland", province: "FL", listing_count: 414 },
  { name: "Lakewood Ranch", slug: "lakewood-ranch", province: "FL", listing_count: 95 },
  { name: "Land O Lakes", slug: "land-o-lakes", province: "FL", listing_count: 76 },
  { name: "Lantana", slug: "lantana", province: "FL", listing_count: 14 },
  { name: "Largo", slug: "largo", province: "FL", listing_count: 135 },
  { name: "Lauderdale By The Sea", slug: "lauderdale-by-the-sea", province: "FL", listing_count: 28 },
  { name: "Lauderdale Lakes", slug: "lauderdale-lakes", province: "FL", listing_count: 17 },
  { name: "Lauderhill", slug: "lauderhill", province: "FL", listing_count: 38 },
  { name: "Lecanto", slug: "lecanto", province: "FL", listing_count: 9 },
  { name: "Leesburg", slug: "leesburg", province: "FL", listing_count: 36 },
  { name: "Lehigh Acres", slug: "lehigh-acres", province: "FL", listing_count: 14 },
  { name: "Lighthouse Point", slug: "lighthouse-point", province: "FL", listing_count: 58 },
  { name: "Lithia", slug: "lithia", province: "FL", listing_count: 45 },
  { name: "Live Oak", slug: "live-oak", province: "FL", listing_count: 48 },
  { name: "Longboat Key", slug: "longboat-key", province: "FL", listing_count: 17 },
  { name: "Longwood", slug: "longwood", province: "FL", listing_count: 177 },
  { name: "Loxahatchee", slug: "loxahatchee", province: "FL", listing_count: 24 },
  { name: "Lutz", slug: "lutz", province: "FL", listing_count: 149 },
  { name: "Lynn Haven", slug: "lynn-haven", province: "FL", listing_count: 17 },
  { name: "Macclenny", slug: "macclenny", province: "FL", listing_count: 15 },
  { name: "Madeira Beach", slug: "madeira-beach", province: "FL", listing_count: 6 },
  { name: "Madison", slug: "madison", province: "FL", listing_count: 5 },
  { name: "Maitland", slug: "maitland", province: "FL", listing_count: 432 },
  { name: "Malabar", slug: "malabar", province: "FL", listing_count: 4 },
  { name: "Mangonia Park", slug: "mangonia-park", province: "FL", listing_count: 4 },
  { name: "Marathon", slug: "marathon", province: "FL", listing_count: 30 },
  { name: "Marco Island", slug: "marco-island", province: "FL", listing_count: 31 },
  { name: "Margate", slug: "margate", province: "FL", listing_count: 28 },
  { name: "Marianna", slug: "marianna", province: "FL", listing_count: 29 },
  { name: "Mary Esther", slug: "mary-esther", province: "FL", listing_count: 6 },
  { name: "Mayo", slug: "mayo", province: "FL", listing_count: 3 },
  { name: "Medley", slug: "medley", province: "FL", listing_count: 4 },
  { name: "Melbourne", slug: "melbourne", province: "FL", listing_count: 411 },
  { name: "Melbourne Beach", slug: "melbourne-beach", province: "FL", listing_count: 22 },
  { name: "Melrose", slug: "melrose", province: "FL", listing_count: 12 },
  { name: "Merritt Island", slug: "merritt-island", province: "FL", listing_count: 71 },
  { name: "Miami", slug: "miami", province: "FL", listing_count: 10430 },
  { name: "Miami Beach", slug: "miami-beach", province: "FL", listing_count: 510 },
  { name: "Miami Gardens", slug: "miami-gardens", province: "FL", listing_count: 54 },
  { name: "Miami Lakes", slug: "miami-lakes", province: "FL", listing_count: 245 },
  { name: "Miami Shores", slug: "miami-shores", province: "FL", listing_count: 63 },
  { name: "Miami Springs", slug: "miami-springs", province: "FL", listing_count: 33 },
  { name: "Micanopy", slug: "micanopy", province: "FL", listing_count: 11 },
  { name: "Middleburg", slug: "middleburg", province: "FL", listing_count: 12 },
  { name: "Middleton", slug: "middleton", province: "FL", listing_count: 6 },
  { name: "Milton", slug: "milton", province: "FL", listing_count: 62 },
  { name: "Mims", slug: "mims", province: "FL", listing_count: 6 },
  { name: "Minneola", slug: "minneola", province: "FL", listing_count: 14 },
  { name: "Miramar", slug: "miramar", province: "FL", listing_count: 193 },
  { name: "Miramar Beach", slug: "miramar-beach", province: "FL", listing_count: 26 },
  { name: "Monticello", slug: "monticello", province: "FL", listing_count: 19 },
  { name: "Montverde", slug: "montverde", province: "FL", listing_count: 9 },
  { name: "Morriston", slug: "morriston", province: "FL", listing_count: 4 },
  { name: "Mount Dora", slug: "mount-dora", province: "FL", listing_count: 55 },
  { name: "Mulberry", slug: "mulberry", province: "FL", listing_count: 3 },
  { name: "Murdock", slug: "murdock", province: "FL", listing_count: 3 },
  { name: "Myakka City", slug: "myakka-city", province: "FL", listing_count: 5 },
  { name: "N Fort Myers", slug: "n-fort-myers", province: "FL", listing_count: 3 },
  { name: "N Miami Beach", slug: "n-miami-beach", province: "FL", listing_count: 9 },
  { name: "Naples", slug: "naples", province: "FL", listing_count: 1055 },
  { name: "Navarre", slug: "navarre", province: "FL", listing_count: 20 },
  { name: "Neptune Beach", slug: "neptune-beach", province: "FL", listing_count: 23 },
  { name: "New Port Richey", slug: "new-port-richey", province: "FL", listing_count: 166 },
  { name: "New Smyrna Beach", slug: "new-smyrna-beach", province: "FL", listing_count: 75 },
  { name: "Newberry", slug: "newberry", province: "FL", listing_count: 31 },
  { name: "Niceville", slug: "niceville", province: "FL", listing_count: 32 },
  { name: "Nobleton", slug: "nobleton", province: "FL", listing_count: 3 },
  { name: "Nokomis", slug: "nokomis", province: "FL", listing_count: 16 },
  { name: "North Bay Village", slug: "north-bay-village", province: "FL", listing_count: 22 },
  { name: "North Fort Myers", slug: "north-fort-myers", province: "FL", listing_count: 25 },
  { name: "North Lauderdale", slug: "north-lauderdale", province: "FL", listing_count: 7 },
  { name: "North Miami", slug: "north-miami", province: "FL", listing_count: 114 },
  { name: "North Miami Beach", slug: "north-miami-beach", province: "FL", listing_count: 118 },
  { name: "North Palm Beach", slug: "north-palm-beach", province: "FL", listing_count: 130 },
  { name: "North Port", slug: "north-port", province: "FL", listing_count: 15 },
  { name: "North Venice", slug: "north-venice", province: "FL", listing_count: 4 },
  { name: "Oakland", slug: "oakland", province: "FL", listing_count: 15 },
  { name: "Oakland Park", slug: "oakland-park", province: "FL", listing_count: 53 },
  { name: "Ocala", slug: "ocala", province: "FL", listing_count: 398 },
  { name: "Ocean Ridge", slug: "ocean-ridge", province: "FL", listing_count: 5 },
  { name: "Ocoee", slug: "ocoee", province: "FL", listing_count: 48 },
  { name: "Odessa", slug: "odessa", province: "FL", listing_count: 70 },
  { name: "Okeechobee", slug: "okeechobee", province: "FL", listing_count: 25 },
  { name: "Oldsmar", slug: "oldsmar", province: "FL", listing_count: 53 },
  { name: "Opa Locka", slug: "opa-locka", province: "FL", listing_count: 4 },
  { name: "Orange City", slug: "orange-city", province: "FL", listing_count: 18 },
  { name: "Orange Park", slug: "orange-park", province: "FL", listing_count: 83 },
  { name: "Orlando", slug: "orlando", province: "FL", listing_count: 4921 },
  { name: "Ormond Beach", slug: "ormond-beach", province: "FL", listing_count: 155 },
  { name: "Osprey", slug: "osprey", province: "FL", listing_count: 19 },
  { name: "Oviedo", slug: "oviedo", province: "FL", listing_count: 118 },
  { name: "Oxford", slug: "oxford", province: "FL", listing_count: 6 },
  { name: "Ozona", slug: "ozona", province: "FL", listing_count: 3 },
  { name: "Pace", slug: "pace", province: "FL", listing_count: 21 },
  { name: "Palatka", slug: "palatka", province: "FL", listing_count: 59 },
  { name: "Palm Bay", slug: "palm-bay", province: "FL", listing_count: 41 },
  { name: "Palm Bch Gdns", slug: "palm-bch-gdns", province: "FL", listing_count: 3 },
  { name: "Palm Beach", slug: "palm-beach", province: "FL", listing_count: 138 },
  { name: "Palm Beach Gardens", slug: "palm-beach-gardens", province: "FL", listing_count: 631 },
  { name: "Palm City", slug: "palm-city", province: "FL", listing_count: 79 },
  { name: "Palm Coast", slug: "palm-coast", province: "FL", listing_count: 60 },
  { name: "Palm Harbor", slug: "palm-harbor", province: "FL", listing_count: 185 },
  { name: "Palm Springs", slug: "palm-springs", province: "FL", listing_count: 9 },
  { name: "Palmetto", slug: "palmetto", province: "FL", listing_count: 33 },
  { name: "Palmetto Bay", slug: "palmetto-bay", province: "FL", listing_count: 117 },
  { name: "Panacea", slug: "panacea", province: "FL", listing_count: 4 },
  { name: "Panama City", slug: "panama-city", province: "FL", listing_count: 250 },
  { name: "Panama City Beach", slug: "panama-city-beach", province: "FL", listing_count: 38 },
  { name: "Parkland", slug: "parkland", province: "FL", listing_count: 130 },
  { name: "Parrish", slug: "parrish", province: "FL", listing_count: 21 },
  { name: "Patrick Afb", slug: "patrick-afb", province: "FL", listing_count: 3 },
  { name: "Patrick Air Force Base", slug: "patrick-air-force-base", province: "FL", listing_count: 3 },
  { name: "Pembroke Pines", slug: "pembroke-pines", province: "FL", listing_count: 290 },
  { name: "Pensacola", slug: "pensacola", province: "FL", listing_count: 802 },
  { name: "Pensacola Beach", slug: "pensacola-beach", province: "FL", listing_count: 9 },
  { name: "Perry", slug: "perry", province: "FL", listing_count: 17 },
  { name: "Pinecrest", slug: "pinecrest", province: "FL", listing_count: 100 },
  { name: "Pinellas Park", slug: "pinellas-park", province: "FL", listing_count: 56 },
  { name: "Plant City", slug: "plant-city", province: "FL", listing_count: 49 },
  { name: "Plantation", slug: "plantation", province: "FL", listing_count: 855 },
  { name: "Poinciana", slug: "poinciana", province: "FL", listing_count: 4 },
  { name: "Pompano Beach", slug: "pompano-beach", province: "FL", listing_count: 230 },
  { name: "Ponce Inlet", slug: "ponce-inlet", province: "FL", listing_count: 4 },
  { name: "Ponte Vedra", slug: "ponte-vedra", province: "FL", listing_count: 94 },
  { name: "Ponte Vedra Beach", slug: "ponte-vedra-beach", province: "FL", listing_count: 188 },
  { name: "Port Charlotte", slug: "port-charlotte", province: "FL", listing_count: 65 },
  { name: "Port Orange", slug: "port-orange", province: "FL", listing_count: 54 },
  { name: "Port Richey", slug: "port-richey", province: "FL", listing_count: 15 },
  { name: "Port Saint Joe", slug: "port-saint-joe", province: "FL", listing_count: 14 },
  { name: "Port Saint Lucie", slug: "port-saint-lucie", province: "FL", listing_count: 209 },
  { name: "Punta Gorda", slug: "punta-gorda", province: "FL", listing_count: 110 },
  { name: "Quincy", slug: "quincy", province: "FL", listing_count: 25 },
  { name: "Redington Shores", slug: "redington-shores", province: "FL", listing_count: 3 },
  { name: "Riverview", slug: "riverview", province: "FL", listing_count: 221 },
  { name: "Riviera Beach", slug: "riviera-beach", province: "FL", listing_count: 23 },
  { name: "Rockledge", slug: "rockledge", province: "FL", listing_count: 75 },
  { name: "Royal Palm Beach", slug: "royal-palm-beach", province: "FL", listing_count: 47 },
  { name: "Ruskin", slug: "ruskin", province: "FL", listing_count: 18 },
  { name: "Safety Harbor", slug: "safety-harbor", province: "FL", listing_count: 39 },
  { name: "Saint Augustine", slug: "saint-augustine", province: "FL", listing_count: 341 },
  { name: "Saint Augustine Beach", slug: "saint-augustine-beach", province: "FL", listing_count: 5 },
  { name: "Saint Cloud", slug: "saint-cloud", province: "FL", listing_count: 47 },
  { name: "Saint James City", slug: "saint-james-city", province: "FL", listing_count: 5 },
  { name: "Saint Johns", slug: "saint-johns", province: "FL", listing_count: 77 },
  { name: "Saint Pete Beach", slug: "saint-pete-beach", province: "FL", listing_count: 33 },
  { name: "Saint Petersburg", slug: "saint-petersburg", province: "FL", listing_count: 1624 },
  { name: "San Antonio", slug: "san-antonio", province: "FL", listing_count: 5 },
  { name: "Sanford", slug: "sanford", province: "FL", listing_count: 176 },
  { name: "Sanibel", slug: "sanibel", province: "FL", listing_count: 17 },
  { name: "Santa Rosa Beach", slug: "santa-rosa-beach", province: "FL", listing_count: 77 },
  { name: "Sarasota", slug: "sarasota", province: "FL", listing_count: 1076 },
  { name: "Satellite Beach", slug: "satellite-beach", province: "FL", listing_count: 27 },
  { name: "Sea Ranch Lakes", slug: "sea-ranch-lakes", province: "FL", listing_count: 6 },
  { name: "Sebastian", slug: "sebastian", province: "FL", listing_count: 24 },
  { name: "Sebring", slug: "sebring", province: "FL", listing_count: 58 },
  { name: "Seffner", slug: "seffner", province: "FL", listing_count: 13 },
  { name: "Seminole", slug: "seminole", province: "FL", listing_count: 99 },
  { name: "Sewalls Point", slug: "sewalls-point", province: "FL", listing_count: 4 },
  { name: "Shalimar", slug: "shalimar", province: "FL", listing_count: 43 },
  { name: "Silver Springs", slug: "silver-springs", province: "FL", listing_count: 7 },
  { name: "Singer Island", slug: "singer-island", province: "FL", listing_count: 3 },
  { name: "Sorrento", slug: "sorrento", province: "FL", listing_count: 12 },
  { name: "South Daytona", slug: "south-daytona", province: "FL", listing_count: 11 },
  { name: "South Miami", slug: "south-miami", province: "FL", listing_count: 90 },
  { name: "South Pasadena", slug: "south-pasadena", province: "FL", listing_count: 12 },
  { name: "Southport", slug: "southport", province: "FL", listing_count: 3 },
  { name: "Southwest Ranches", slug: "southwest-ranches", province: "FL", listing_count: 20 },
  { name: "Spring Hill", slug: "spring-hill", province: "FL", listing_count: 79 },
  { name: "Starke", slug: "starke", province: "FL", listing_count: 9 },
  { name: "Stuart", slug: "stuart", province: "FL", listing_count: 364 },
  { name: "Summerfield", slug: "summerfield", province: "FL", listing_count: 10 },
  { name: "Summerland Key", slug: "summerland-key", province: "FL", listing_count: 4 },
  { name: "Sun City Center", slug: "sun-city-center", province: "FL", listing_count: 16 },
  { name: "Sun City Ctr", slug: "sun-city-ctr", province: "FL", listing_count: 3 },
  { name: "Sunny Isles Beach", slug: "sunny-isles-beach", province: "FL", listing_count: 38 },
  { name: "Sunrise", slug: "sunrise", province: "FL", listing_count: 237 },
  { name: "Surfside", slug: "surfside", province: "FL", listing_count: 26 },
  { name: "Tallahassee", slug: "tallahassee", province: "FL", listing_count: 2856 },
  { name: "Tamarac", slug: "tamarac", province: "FL", listing_count: 53 },
  { name: "Tampa", slug: "tampa", province: "FL", listing_count: 6454 },
  { name: "Tarpon Springs", slug: "tarpon-springs", province: "FL", listing_count: 58 },
  { name: "Tavares", slug: "tavares", province: "FL", listing_count: 122 },
  { name: "Tavernier", slug: "tavernier", province: "FL", listing_count: 36 },
  { name: "Temple Ter", slug: "temple-ter", province: "FL", listing_count: 6 },
  { name: "Temple Terrace", slug: "temple-terrace", province: "FL", listing_count: 38 },
  { name: "Tequesta", slug: "tequesta", province: "FL", listing_count: 32 },
  { name: "Terra Ceia", slug: "terra-ceia", province: "FL", listing_count: 3 },
  { name: "The Villages", slug: "the-villages", province: "FL", listing_count: 52 },
  { name: "Thonotosassa", slug: "thonotosassa", province: "FL", listing_count: 6 },
  { name: "Tierra Verde", slug: "tierra-verde", province: "FL", listing_count: 18 },
  { name: "Titusville", slug: "titusville", province: "FL", listing_count: 45 },
  { name: "Treasure Island", slug: "treasure-island", province: "FL", listing_count: 14 },
  { name: "Trenton", slug: "trenton", province: "FL", listing_count: 12 },
  { name: "Trinity", slug: "trinity", province: "FL", listing_count: 42 },
  { name: "University Park", slug: "university-park", province: "FL", listing_count: 7 },
  { name: "Valrico", slug: "valrico", province: "FL", listing_count: 58 },
  { name: "Venice", slug: "venice", province: "FL", listing_count: 107 },
  { name: "Vero Beach", slug: "vero-beach", province: "FL", listing_count: 312 },
  { name: "Viera", slug: "viera", province: "FL", listing_count: 92 },
  { name: "Village Of Palmetto Bay", slug: "village-of-palmetto-bay", province: "FL", listing_count: 5 },
  { name: "Wauchula", slug: "wauchula", province: "FL", listing_count: 8 },
  { name: "Weeki Wachee", slug: "weeki-wachee", province: "FL", listing_count: 6 },
  { name: "Wellington", slug: "wellington", province: "FL", listing_count: 131 },
  { name: "Wesley Chapel", slug: "wesley-chapel", province: "FL", listing_count: 81 },
  { name: "West Melbourne", slug: "west-melbourne", province: "FL", listing_count: 16 },
  { name: "West Miami", slug: "west-miami", province: "FL", listing_count: 6 },
  { name: "West Palm Bch", slug: "west-palm-bch", province: "FL", listing_count: 7 },
  { name: "West Palm Beach", slug: "west-palm-beach", province: "FL", listing_count: 2251 },
  { name: "Westlake", slug: "westlake", province: "FL", listing_count: 5 },
  { name: "Weston", slug: "weston", province: "FL", listing_count: 314 },
  { name: "Wildlight", slug: "wildlight", province: "FL", listing_count: 3 },
  { name: "Wildwood", slug: "wildwood", province: "FL", listing_count: 11 },
  { name: "Williston", slug: "williston", province: "FL", listing_count: 7 },
  { name: "Wilton Manors", slug: "wilton-manors", province: "FL", listing_count: 45 },
  { name: "Wimauma", slug: "wimauma", province: "FL", listing_count: 5 },
  { name: "Windermere", slug: "windermere", province: "FL", listing_count: 93 },
  { name: "Winter Garden", slug: "winter-garden", province: "FL", listing_count: 156 },
  { name: "Winter Haven", slug: "winter-haven", province: "FL", listing_count: 94 },
  { name: "Winter Park", slug: "winter-park", province: "FL", listing_count: 633 },
  { name: "Winter Springs", slug: "winter-springs", province: "FL", listing_count: 61 },
  { name: "Yalaha", slug: "yalaha", province: "FL", listing_count: 4 },
  { name: "Yulee", slug: "yulee", province: "FL", listing_count: 31 },
  { name: "Zellwood", slug: "zellwood", province: "FL", listing_count: 3 },
  { name: "Zephyrhills", slug: "zephyrhills", province: "FL", listing_count: 16 },
];

export const CITIES = [...CANONICAL_CITIES, ...US_CITIES].map((c) => ({
  name: c.name,
  slug: c.slug,
  province: c.province,
}));

export const LISTING_TYPES = [
  { name: "Family Lawyer", slug: "family-lawyer", description: "Divorce, custody, child support" },
  { name: "Immigration Lawyer", slug: "immigration-lawyer", description: "Green card, citizenship, asylum, deportation defense" },
  { name: "Criminal Defense Lawyer", slug: "criminal-lawyer", description: "DUI, felony, misdemeanor defense" },
  { name: "Personal Injury Lawyer", slug: "personal-injury-lawyer", description: "Auto accidents, slip and fall, medical malpractice" },
  { name: "Estate Planning Lawyer", slug: "estate-lawyer", description: "Wills, trusts, probate" },
  { name: "Real Estate Lawyer", slug: "real-estate-lawyer", description: "Closings, title disputes, property transactions" },
  { name: "Business Lawyer", slug: "business-lawyer", description: "Formation, contracts, commercial disputes" },
  { name: "Employment Lawyer", slug: "employment-lawyer", description: "Wrongful termination, discrimination, wage disputes" },
  { name: "Bankruptcy Lawyer", slug: "bankruptcy-lawyer", description: "Chapter 7, Chapter 13, debt relief" },
  { name: "Tax Lawyer", slug: "tax-lawyer", description: "IRS disputes, tax court, planning" },
];

export const BRAND = {
  siteName: verticalConfig.name,
  siteUrl: `https://${verticalConfig.domain}`,
  supportEmail: verticalConfig.supportEmail,
};

export function getRegionBySlug(slug: string) {
  return REGIONS.find((r) => r.slug === slug.toLowerCase()) || null;
}

export function getListingTypeBySlug(slug: string) {
  return LISTING_TYPES.find((t) => t.slug === slug) || null;
}

export function getCityBySlug(provinceSlug: string, citySlug: string) {
  const province = provinceSlug.toUpperCase();
  return CITIES.find((c: any) => c.province === province && c.slug === citySlug) || null;
}

export const PROVINCES: Record<string, string> = PROVINCE_MAP;

// Locale-independent thousands separator. The Vercel Node runtime ships
// without full-ICU, so Number.toLocaleString("en-US") returns no grouping —
// format manually so counts render "187,864" not "187864" (#3 credibility).
export function formatCount(n: number): string {
  return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
